// Churchill Downs — 2026-04-30
// Generated by scripts/gen_cd_ts.py from data/cd-2026-04-30/raw-entries.json
// Data source: BRIS Ultimate PPs PDF (parsed via scripts/parse_bris_pdf.py).
// Track bias uses CD spring-meet defaults (cd-context.ts CD_DEFAULT_BIASES).

import type { StaticRace, StaticHorse } from "./static-types";

const h = (
  program: string, name: string, ml: number, style: string,
  beyers: number[], days: number, weight: number,
  extras: Partial<StaticHorse> = {}
): StaticHorse => ({
  program, name, mlOdds: ml, style,
  last3Beyer: beyers, daysSinceLast: days, weight,
  ...extras,
});

// ── R1 — Clm  50000b 6f Dirt $78,000 ──
const race1: StaticRace = {
  raceNumber: 1, postTime: "12:45 PM",
  raceType: "Clm  50000b", distance: "6f", surface: "Dirt", purse: 78000, condition: "Fast",
  trackBias: {
    surface: "Dirt", distanceLabel: "6.0f",
    speedBiasPct: 85, railBias: "+",
    eIV: 1.45, epIV: 1.6, pIV: 0.65, sIV: 0.35,
    post1to3IV: 1.55, post4to7IV: 1.0, post8plusIV: 0.62,
  },
  horses: [
    h("1", "Banned for Life", 1.0, "E", [87, 88, 90], 74, 124, { primePower: 127.0, earlyPaceLast: 91, latePaceLast: 84, mudPct: 14 }), // jockey: Luis Saez, trainer: Albert M. Stall Jr., post: 1
    h("2", "Optical", 11.0, "S", [71, 71, 91], 167, 124, { primePower: 119.8, earlyPaceLast: 79, latePaceLast: 69, mudPct: 15 }), // jockey: James Graham, trainer: J. Keith Desormeaux, post: 2
    h("3", "Surf City", 16.0, "S", [75, 72, 88], 26, 124, { primePower: 122.7, earlyPaceLast: 78, latePaceLast: 85, mudPct: 18 }), // jockey: Junior Alvarado, trainer: Victoria H. Oliver, post: 3
    h("4", "Star's Image", 4.5, "EP", [62, 0, 0], 108, 124, { primePower: 122.0, mudPct: 11 }), // jockey: Irad Ortiz Jr., trainer: Joe Sharp, post: 4
    h("5", "Keep On Moving", 14.0, "P", [79, 81, 81], 34, 124, { primePower: 120.1, earlyPaceLast: 80, latePaceLast: 80, mudPct: 18 }), // jockey: Jose L. Ortiz, trainer: J. Kent Sweezey, post: 5
    h("6", "You Ain't Poppn", 2.5, "EP", [83, 86, 78], 39, 124, { primePower: 124.9, earlyPaceLast: 81, latePaceLast: 81, mudPct: 15 }), // jockey: Micah J. Husbands, trainer: Saffie A. Joseph Jr., post: 6
    h("7", "Tejon Pass", 10.0, "EP", [77, 90, 84], 137, 124, { primePower: 123.3, earlyPaceLast: 91, latePaceLast: 74, mudPct: 18 }), // jockey: William Antongeorgi III, trainer: William E. Morey, post: 7
  ],
};

// ── R2 — Alw  127000n1x 6f Dirt $127,000 ──
const race2: StaticRace = {
  raceNumber: 2, postTime: "1:15 PM",
  raceType: "Alw  127000n1x", distance: "6f", surface: "Dirt", purse: 127000, condition: "Fast",
  trackBias: {
    surface: "Dirt", distanceLabel: "6.0f",
    speedBiasPct: 85, railBias: "+",
    eIV: 1.45, epIV: 1.6, pIV: 0.65, sIV: 0.35,
    post1to3IV: 1.55, post4to7IV: 1.0, post8plusIV: 0.62,
  },
  horses: [
    h("2", "She'z the Law", 1.6, "P", [68, 74, 0], 81, 124, { primePower: 114.7, earlyPaceLast: 90, latePaceLast: 70, mudPct: 16 }), // jockey: Luis Saez, trainer: Gregory D. Foley, post: 2
    h("3", "Cotillard", 4.5, "E", [68, 80, 72], 42, 124, { primePower: 113.9, earlyPaceLast: 89, latePaceLast: 69, mudPct: 11 }), // jockey: J.J. Meza, trainer: Luis E. Seglin, post: 3
    h("5", "Shared Vision", 0.5, "EP", [82, 69, 85], 222, 124, { primePower: 122.7, earlyPaceLast: 89, latePaceLast: 85, mudPct: 11 }), // jockey: Edgar Morales, trainer: George R. Arnold II, post: 5
  ],
};

// ── R3 — MC 30000 1m Dirt $57,000 ──
const race3: StaticRace = {
  raceNumber: 3, postTime: "1:45 PM",
  raceType: "MC 30000", distance: "1m", surface: "Dirt", purse: 57000, condition: "Fast",
  trackBias: {
    surface: "Dirt", distanceLabel: "8.5f",
    speedBiasPct: 62, railBias: "+",
    eIV: 1.1, epIV: 1.2, pIV: 0.9, sIV: 0.8,
    post1to3IV: 1.25, post4to7IV: 1.0, post8plusIV: 0.78,
  },
  horses: [
    h("1", "Market Strategy", 11.0, "NA", [58, 0, 0], 42, 126, { primePower: 108.7, earlyPaceLast: 88, latePaceLast: 59, mudPct: 8 }), // jockey: Axel Concepcion, trainer: Michael A. Tomlinson, post: 1
    h("2", "Fresh Out", 8.0, "P", [65, 68, 53], 21, 118, { primePower: 110.7, earlyPaceLast: 85, latePaceLast: 68, mudPct: 15 }), // jockey: Christopher Elliott, trainer: Kenneth G. Mcpeek, post: 2
    h("3", "My Secret Dreams", 4.0, "P", [68, 46, 75], 33, 118, { primePower: 104.6, earlyPaceLast: 57, latePaceLast: 94, mudPct: 13 }), // jockey: Edgar Morales, trainer: Genaro Garcia, post: 3
    h("4", "Silvertown", 7.0, "S", [65, 69, 65], 26, 118, { primePower: 107.7, earlyPaceLast: 90, latePaceLast: 72, mudPct: 23 }), // jockey: Joseph D. Ramos, trainer: Genaro Garcia, post: 4
    h("5", "Spotted", 2.0, "P", [70, 0, 0], 39, 118, { primePower: 112.6, earlyPaceLast: 79, latePaceLast: 76, mudPct: 8 }), // jockey: Tyler Gaffalione, trainer: Lauren Robson, post: 5
    h("6", "Kopiana", 5.0, "E", [64, 71, 0], 26, 118, { primePower: 113.9, earlyPaceLast: 96, latePaceLast: 63, mudPct: 17 }), // jockey: Luis Saez, trainer: Ron Moquett, post: 6
    h("8", "Motown Sound", 14.0, "NA", [47, 0, 0], 185, 118, { primePower: 97.6, mudPct: 15 }), // jockey: Constantino Roman, trainer: Hutch Holsapple, post: 8
    h("9", "Souperrazzledazzle", 4.0, "P", [67, 69, 61], 33, 118, { primePower: 107.4, earlyPaceLast: 59, latePaceLast: 94, mudPct: 15 }), // jockey: Jaime A. Torres, trainer: Jordan Blair, post: 9
  ],
};

// ── R4 — MC 50000 1 1/16m Turf $67,000 ──
const race4: StaticRace = {
  raceNumber: 4, postTime: "2:18 PM",
  raceType: "MC 50000", distance: "1 1/16m", surface: "Turf", purse: 67000, condition: "Fast",
  trackBias: {
    surface: "Turf", distanceLabel: "routes",
    speedBiasPct: 45, railBias: "+",
    eIV: 0.55, epIV: 1.35, pIV: 1.25, sIV: 0.85,
    post1to3IV: 1.4, post4to7IV: 0.95, post8plusIV: 0.42,
  },
  horses: [
    h("1", "Hardly Ready", 16.0, "P", [72, 68, 0], 40, 118, { primePower: 107.1, earlyPaceLast: 83, latePaceLast: 81, mudPct: 15 }), // jockey: William Antongeorgi III, trainer: William E. Morey, post: 1
    h("3", "Devices", 5.0, "NA", [0, 0, 0], 0, 118, { mudPct: 9 }), // jockey: Irad Ortiz Jr., trainer: Joe Sharp, post: 3
    h("4", "Lexico", 6.0, "EP", [78, 72, 78], 18, 118, { primePower: 114.7, earlyPaceLast: 71, latePaceLast: 86, mudPct: 0 }), // jockey: Julien R. Leparoux, trainer: Donald J. Habeeb, post: 4
    h("5", "Modern Escape", 32.0, "EP", [62, 67, 57], 17, 111, { primePower: 101.4, earlyPaceLast: 65, latePaceLast: 72, mudPct: 15 }), // jockey: Luis D. Perez, trainer: Tito Moreno, post: 5
    h("6", "Play On Player", 20.0, "NA", [65, 68, 0], 39, 118, { primePower: 107.2, earlyPaceLast: 67, latePaceLast: 66, mudPct: 14 }), // jockey: Danny Sheehy, trainer: Michelle Lovell, post: 6
    h("7", "Mother Lode", 27.0, "NA", [62, 0, 0], 62, 118, { primePower: 98.5, earlyPaceLast: 87, latePaceLast: 67, mudPct: 13 }), // jockey: James Graham, trainer: Destin G. Heath, post: 7
    h("8", "Theoretical", 2.0, "NA", [76, 76, 65], 31, 118, { primePower: 122.3, earlyPaceLast: 73, latePaceLast: 87, mudPct: 19 }), // jockey: Junior Alvarado, trainer: Riley Mott, post: 8
    h("9", "Ocean Ripple", 23.0, "S", [56, 74, 0], 326, 126, { primePower: 90.0, mudPct: 10 }), // jockey: Jaime A. Torres, trainer: David Jacobson, post: 9
    h("10", "Lady Faye", 16.0, "P", [78, 65, 69], 34, 118, { primePower: 107.7, earlyPaceLast: 82, latePaceLast: 80, mudPct: 18 }), // jockey: Gerardo Corrales, trainer: Joe B. Roberts, post: 10
    h("11", "Plot", 7.0, "S", [71, 75, 0], 76, 126, { primePower: 115.4, earlyPaceLast: 72, latePaceLast: 76, mudPct: 17 }), // jockey: Brian J. Hernandez Jr., trainer: Thomas Drury Jr., post: 11
    h("12", "Breaking Hearts", 5.0, "E", [71, 61, 67], 53, 118, { primePower: 119.3, earlyPaceLast: 95, latePaceLast: 60, mudPct: 15 }), // jockey: Jose L. Ortiz, trainer: Cherie Devaux, post: 12
    h("13", "English Harbour", 17.0, "NA", [0, 0, 0], 33, 126, { primePower: 117.2, mudPct: 15 }), // jockey: John R. Velazquez, trainer: Lauren Robson, post: 13
  ],
};

// ── R5 — MC 12500 1m Dirt $35,000 ──
const race5: StaticRace = {
  raceNumber: 5, postTime: "2:52 PM",
  raceType: "MC 12500", distance: "1m", surface: "Dirt", purse: 35000, condition: "Fast",
  trackBias: {
    surface: "Dirt", distanceLabel: "8.5f",
    speedBiasPct: 62, railBias: "+",
    eIV: 1.1, epIV: 1.2, pIV: 0.9, sIV: 0.8,
    post1to3IV: 1.25, post4to7IV: 1.0, post8plusIV: 0.78,
  },
  horses: [
    h("1", "Chasing Gray", 4.5, "E", [38, 39, 65], 19, 118, { primePower: 97.4, earlyPaceLast: 82, latePaceLast: 42, mudPct: 15 }), // jockey: Jaime A. Torres, trainer: Grant T. Forster, post: 1
    h("2", "Old Trace", 25.0, "S", [56, 71, 63], 23, 126, { primePower: 100.8, earlyPaceLast: 77, latePaceLast: 57, mudPct: 15 }), // jockey: Alex Achard, trainer: Michael S. Warpool, post: 2
    h("3", "Jinxzi", 4.0, "E", [64, 70, 75], 40, 126, { primePower: 108.8, earlyPaceLast: 67, latePaceLast: 68, mudPct: 16 }), // jockey: Victor R. Carrasco, trainer: Ian R. Wilkes, post: 3
    h("4", "Cliffs of Dover", 10.0, "S", [60, 72, 57], 55, 126, { primePower: 103.8, earlyPaceLast: 70, latePaceLast: 60, mudPct: 19 }), // jockey: James Graham, trainer: Destin G. Heath, post: 4
    h("5", "Paired", 10.0, "NA", [59, 62, 53], 33, 113, { primePower: 101.2, earlyPaceLast: 59, latePaceLast: 79, mudPct: 12 }), // jockey: Summer Pauly, trainer: David Jacobson, post: 5
    h("6", "Big Rog", 7.0, "S", [51, 73, 65], 17, 126, { primePower: 104.8, earlyPaceLast: 59, latePaceLast: 63, mudPct: 17 }), // jockey: Danny Sheehy, trainer: Barry L. King, post: 6
    h("8", "Ando", 6.0, "P", [70, 67, 65], 40, 126, { primePower: 107.3, earlyPaceLast: 63, latePaceLast: 79, mudPct: 18 }), // jockey: Mario Gutierrez, trainer: Fausto Gutierrez, post: 8
    h("9", "Chiquita's Way", 17.0, "P", [62, 61, 0], 34, 103, { primePower: 99.9, mudPct: 15 }), // jockey: Pedro Pena, trainer: Andres Cambray, post: 9
    h("10", "Spring St. Dreamer", 19.0, "NA", [61, 60, 0], 53, 118, { primePower: 103.3, earlyPaceLast: 76, latePaceLast: 59, mudPct: 12 }), // jockey: Axel Concepcion, trainer: Matt A. Shirer, post: 10
    h("11", "The Reinbow Factor", 28.0, "NA", [64, 65, 61], 19, 126, { primePower: 104.8, earlyPaceLast: 69, latePaceLast: 76, mudPct: 13 }), // jockey: Gabriel Saez, trainer: Michael R. Thompson, post: 11
    h("12", "Tregetour", 3.5, "S", [58, 66, 63], 17, 118, { primePower: 106.2, earlyPaceLast: 65, latePaceLast: 67, mudPct: 14 }), // jockey: Luan Machado, trainer: Ben Colebrook, post: 12
    h("13", "Silver Dime", 27.0, "NA", [40, 0, 0], 19, 118, { primePower: 93.2, earlyPaceLast: 68, latePaceLast: 47, mudPct: 23 }), // jockey: Joseph D. Ramos, trainer: Corie Anderson, post: 13
  ],
};

// ── R6 — UAEPrsCp-G1 1 1/16m Dirt $400,000 ──
const race6: StaticRace = {
  raceNumber: 6, postTime: "3:29 PM",
  raceType: "UAEPrsCp-G1", distance: "1 1/16m", surface: "Dirt", purse: 400000, condition: "Fast",
  trackBias: {
    surface: "Dirt", distanceLabel: "8.5f",
    speedBiasPct: 62, railBias: "+",
    eIV: 1.1, epIV: 1.2, pIV: 0.9, sIV: 0.8,
    post1to3IV: 1.25, post4to7IV: 1.0, post8plusIV: 0.78,
  },
  horses: [
    h("1", "Wma Wild Kisses", 20.0, "NA", [0, 0, 0], 32, 117, { mudPct: 0 }), // jockey: Joseph Rocco Jr., trainer: Thunder Johnson, post: 1
    h("2", "Aa Take a Chance", 10.0, "NA", [0, 0, 0], 26, 124, { mudPct: 18 }), // jockey: James Graham, trainer: Nicole Ruggeri, post: 2
    h("3", "Highh Stakes", 20.0, "NA", [0, 0, 0], 32, 117, { mudPct: 43 }), // jockey: Corey J. Lanerie, trainer: Thunder Johnson, post: 3
    h("4", "Diamond Gem Aa", 2.5, "NA", [0, 0, 0], 45, 126, { mudPct: 21 }), // jockey: Irad Ortiz Jr., trainer: Jerenesto Torrez, post: 4
    h("5", "Highh Country", 10.0, "NA", [0, 0, 0], 13, 122, { mudPct: 41 }), // jockey: Joel Rosario, trainer: Nicole Ruggeri, post: 5
    h("6", "Rb Badonkadonk", 1.2, "NA", [0, 0, 0], 32, 117, { mudPct: 100 }), // jockey: Ernesto Valdez-Jiminez, trainer: Jerenesto Torrez, post: 6
    h("7", "Wma Grand Finale", 15.0, "NA", [0, 0, 0], 25, 124, { mudPct: 16 }), // jockey: Luan Machado, trainer: Juan A. Ascencio, post: 7
    h("8", "Wma Smoke Signal", 8.0, "NA", [0, 0, 0], 45, 124, { mudPct: 16 }), // jockey: Luis Saez, trainer: Carlos A. Padilla, post: 8
    h("9", "Quick Rae Aa", 12.0, "NA", [0, 0, 0], 25, 124, { mudPct: 21 }), // jockey: Gabriel Saez, trainer: Nicole Ruggeri, post: 9
  ],
};

// ── R7 — Mdn 120k 1 1/16m Turf $120,000 ──
const race7: StaticRace = {
  raceNumber: 7, postTime: "4:03 PM",
  raceType: "Mdn 120k", distance: "1 1/16m", surface: "Turf", purse: 120000, condition: "Fast",
  trackBias: {
    surface: "Turf", distanceLabel: "routes",
    speedBiasPct: 45, railBias: "+",
    eIV: 0.55, epIV: 1.35, pIV: 1.25, sIV: 0.85,
    post1to3IV: 1.4, post4to7IV: 0.95, post8plusIV: 0.42,
  },
  horses: [
    h("1", "Honfleur", 1.8, "P", [79, 85, 70], 25, 118, { primePower: 136.1, earlyPaceLast: 79, latePaceLast: 88, mudPct: 20 }), // jockey: Flavien Prat, trainer: Chad C. Brown, post: 1
    h("2", "Perrylu", 20.0, "NA", [65, 74, 0], 19, 126, { primePower: 109.7, earlyPaceLast: 80, latePaceLast: 76, mudPct: 19 }), // jockey: Luis Saez, trainer: Victoria H. Oliver, post: 2
    h("3", "Strada Del Sogno", 20.0, "E", [69, 80, 75], 151, 118, { primePower: 106.7, earlyPaceLast: 85, latePaceLast: 71, mudPct: 14 }), // jockey: Gabriel Saez, trainer: Genevieve Londono, post: 3
    h("4", "Cape Sounion", 3.0, "NA", [67, 0, 0], 39, 118, { primePower: 130.8, earlyPaceLast: 89, latePaceLast: 63, mudPct: 11 }), // jockey: Tyler Gaffalione, trainer: Brendan P. Walsh, post: 4
    h("5", "Heavenly Melody", 4.5, "S", [77, 80, 0], 39, 118, { primePower: 125.7, earlyPaceLast: 81, latePaceLast: 81, mudPct: 9 }), // jockey: Irad Ortiz Jr., trainer: Joe Sharp, post: 5
    h("6", "Twinklee", 15.0, "E", [76, 83, 76], 46, 118, { primePower: 115.4, earlyPaceLast: 89, latePaceLast: 68, mudPct: 17 }), // jockey: Jareth Loveberry, trainer: Wayne M. Catalano, post: 6
    h("7", "Vow to Resiliency", 6.0, "S", [83, 79, 82], 24, 126, { primePower: 126.3, earlyPaceLast: 91, latePaceLast: 87, mudPct: 20 }), // jockey: Joel Rosario, trainer: Philip Damato, post: 7
    h("8", "Sammy the Shark", 50.0, "NA", [41, 0, 0], 131, 118, { primePower: 92.3, earlyPaceLast: 78, latePaceLast: 49, mudPct: 10 }), // jockey: Danny Sheehy, trainer: Paul Mcentee, post: 8
    h("9", "Wing Queen", 20.0, "EP", [69, 81, 68], 33, 126, { primePower: 123.0, earlyPaceLast: 87, latePaceLast: 72, mudPct: 18 }), // jockey: Junior Alvarado, trainer: Michelle Lovell, post: 9
    h("10", "Bourbiana", 8.0, "NA", [0, 0, 0], 0, 118, { mudPct: 20 }), // jockey: John R. Velazquez, trainer: William Walden, post: 10
    h("11", "Cynical Humor", 15.0, "P", [73, 70, 0], 118, 118, { primePower: 121.7, earlyPaceLast: 69, latePaceLast: 78, mudPct: 20 }), // jockey: Gerardo Corrales, trainer: Wesley A. Ward, post: 11
    h("12", "Treat Yourself", 30.0, "NA", [0, 0, 0], 0, 118, { mudPct: 17 }), // jockey: Cristian A. Torres, trainer: Robert Medina, post: 12
  ],
};

// ── R8 — Alw  50000s 7f Dirt $83,000 ──
const race8: StaticRace = {
  raceNumber: 8, postTime: "4:40 PM",
  raceType: "Alw  50000s", distance: "7f", surface: "Dirt", purse: 83000, condition: "Fast",
  trackBias: {
    surface: "Dirt", distanceLabel: "6.0f",
    speedBiasPct: 85, railBias: "+",
    eIV: 1.45, epIV: 1.6, pIV: 0.65, sIV: 0.35,
    post1to3IV: 1.55, post4to7IV: 1.0, post8plusIV: 0.62,
  },
  horses: [
    h("1", "Angel Bella", 2.5, "P", [85, 84, 69], 165, 124, { primePower: 120.9, earlyPaceLast: 72, latePaceLast: 88, mudPct: 14 }), // jockey: Luan Machado, trainer: D. Whitworth Beckman, post: 1
    h("2", "Our Shenanigan", 3.0, "EP", [88, 83, 70], 34, 124, { primePower: 126.3, earlyPaceLast: 91, latePaceLast: 87, mudPct: 17 }), // jockey: Flavien Prat, trainer: Amelia J. Green, post: 2
    h("3", "Late to the Game", 8.0, "P", [78, 84, 84], 34, 124, { primePower: 125.0, earlyPaceLast: 88, latePaceLast: 82, mudPct: 17 }), // jockey: Junior Alvarado, trainer: Robert Medina, post: 3
    h("5", "Tearin'up My Heart", 15.0, "S", [76, 75, 73], 82, 118, { primePower: 118.6, earlyPaceLast: 80, latePaceLast: 76, mudPct: 18 }), // jockey: Edgar Morales, trainer: Genaro Garcia, post: 5
    h("6", "Jensco", 1.8, "E", [94, 76, 60], 54, 124, { primePower: 123.9, earlyPaceLast: 89, latePaceLast: 102, mudPct: 13 }), // jockey: Irad Ortiz Jr., trainer: Robert B. Hess Jr., post: 6
    h("7", "Madeline's Promise", 6.0, "E", [81, 76, 70], 292, 124, { primePower: 116.8, earlyPaceLast: 89, latePaceLast: 82, mudPct: 28 }), // jockey: Rajiv Maragh, trainer: Dale L. Romans, post: 7
  ],
};

// ── R9 — OpningVrsL350K 1m Turf $350,000 ──
const race9: StaticRace = {
  raceNumber: 9, postTime: "5:14 PM",
  raceType: "OpningVrsL350K", distance: "1m", surface: "Turf", purse: 350000, condition: "Fast",
  trackBias: {
    surface: "Turf", distanceLabel: "routes",
    speedBiasPct: 45, railBias: "+",
    eIV: 0.55, epIV: 1.35, pIV: 1.25, sIV: 0.85,
    post1to3IV: 1.4, post4to7IV: 0.95, post8plusIV: 0.42,
  },
  horses: [
    h("2", "Minaret Station", 10.0, "P", [88, 87, 66], 305, 120, { primePower: 143.6, earlyPaceLast: 72, latePaceLast: 96, mudPct: 16 }), // jockey: Cristian A. Torres, trainer: William Walden, post: 2
    h("3", "Balnikhov", 15.0, "S", [99, 92, 83], 39, 120, { primePower: 150.4, earlyPaceLast: 84, latePaceLast: 96, mudPct: 0 }), // jockey: Joel Rosario, trainer: Philip Damato, post: 3
    h("4", "Quatrocento", 3.0, "E", [92, 97, 95], 32, 122, { primePower: 161.3, earlyPaceLast: 91, latePaceLast: 88, mudPct: 14 }), // jockey: Julien R. Leparoux, trainer: Fausto Gutierrez, post: 4
    h("5", "Chasing the Crown", 15.0, "S", [99, 89, 95], 39, 120, { primePower: 161.6, earlyPaceLast: 89, latePaceLast: 94, mudPct: 16 }), // jockey: Juan J. Hernandez, trainer: Michael J. Maker, post: 5
    h("6", "Giocoso", 12.0, "P", [92, 88, 87], 158, 122, { primePower: 147.7, earlyPaceLast: 82, latePaceLast: 90, mudPct: 20 }), // jockey: James Graham, trainer: J. Keith Desormeaux, post: 6
    h("7", "Mi Bago", 15.0, "E", [87, 92, 88], 53, 120, { primePower: 139.4, earlyPaceLast: 100, latePaceLast: 61, mudPct: 22 }), // jockey: John R. Velazquez, trainer: Mark E. Casse, post: 7
    h("8", "Lagynos", 1.6, "P", [103, 101, 92], 39, 124, { primePower: 171.0, earlyPaceLast: 93, latePaceLast: 101, mudPct: 16 }), // jockey: Jose L. Ortiz, trainer: Steven M. Asmussen, post: 8
    h("9", "West Hollywood", 8.0, "EP", [89, 94, 87], 40, 120, { primePower: 149.6, earlyPaceLast: 81, latePaceLast: 89, mudPct: 18 }), // jockey: Flavien Prat, trainer: Brad H. Cox, post: 9
  ],
};

// ── R10 — StMatthwsB200K 6f Dirt $200,000 ──
const race10: StaticRace = {
  raceNumber: 10, postTime: "5:50 PM",
  raceType: "StMatthwsB200K", distance: "6f", surface: "Dirt", purse: 200000, condition: "Fast",
  trackBias: {
    surface: "Dirt", distanceLabel: "6.0f",
    speedBiasPct: 85, railBias: "+",
    eIV: 1.45, epIV: 1.6, pIV: 0.65, sIV: 0.35,
    post1to3IV: 1.55, post4to7IV: 1.0, post8plusIV: 0.62,
  },
  horses: [
    h("1", "Concrete Glory", 8.0, "E", [94, 97, 70], 32, 123, { primePower: 139.1, earlyPaceLast: 92, latePaceLast: 88, mudPct: 15 }), // jockey: Irad Ortiz Jr., trainer: Saffie A. Joseph Jr., post: 1
    h("2", "Built", 3.0, "EP", [100, 87, 91], 47, 118, { primePower: 135.3, earlyPaceLast: 95, latePaceLast: 92, mudPct: 16 }), // jockey: Jareth Loveberry, trainer: Wayne M. Catalano, post: 2
    h("4", "Billal", 20.0, "P", [87, 76, 90], 59, 118, { primePower: 129.1, earlyPaceLast: 83, latePaceLast: 90, mudPct: 17 }), // jockey: Junior Alvarado, trainer: William I. Mott, post: 4
    h("5", "Lofty Adjudicator", 30.0, "EP", [91, 93, 92], 129, 118, { primePower: 130.4, earlyPaceLast: 88, latePaceLast: 96, mudPct: 15 }), // jockey: Sonny Leon, trainer: Anna Navarrete, post: 5
    h("6", "Back Em Up", 6.0, "EP", [95, 77, 97], 32, 118, { primePower: 133.6, earlyPaceLast: 87, latePaceLast: 95, mudPct: 18 }), // jockey: Luis Saez, trainer: Bobby S. Dibona, post: 6
    h("8", "Bourbon Bash", 10.0, "EP", [88, 86, 91], 25, 123, { primePower: 136.2, earlyPaceLast: 96, latePaceLast: 79, mudPct: 15 }), // jockey: Joel Rosario, trainer: Steven M. Asmussen, post: 8
    h("9", "Maximum Bourbon", 4.5, "E", [97, 92, 94], 47, 118, { primePower: 135.4, earlyPaceLast: 93, latePaceLast: 90, mudPct: 21 }), // jockey: Flavien Prat, trainer: Philip Damato, post: 9
    h("11", "Air Invasion", 30.0, "P", [85, 82, 82], 32, 118, { primePower: 120.9, earlyPaceLast: 81, latePaceLast: 91, mudPct: 18 }), // jockey: Gaddiel A. Martinez, trainer: Martin Paramo, post: 11
  ],
};

// ── R11 — Mamzelle-G3 5 1/2f Turf $300,000 ──
const race11: StaticRace = {
  raceNumber: 11, postTime: "6:22 PM",
  raceType: "Mamzelle-G3", distance: "5 1/2f", surface: "Turf", purse: 300000, condition: "Fast",
  trackBias: {
    surface: "Turf", distanceLabel: "5.5f",
    speedBiasPct: 55, railBias: "+",
    eIV: 0.55, epIV: 1.6, pIV: 1.2, sIV: 0.65,
    post1to3IV: 1.55, post4to7IV: 0.9, post8plusIV: 0.4,
  },
  horses: [
    h("1", "Snappy Comeback", 8.0, "EP", [82, 88, 0], 209, 118, { primePower: 128.0, earlyPaceLast: 88, latePaceLast: 79, mudPct: 14 }), // jockey: Junior Alvarado, trainer: Jose F. D'Angelo, post: 1
    h("2", "Ifyousaidso", 20.0, "E", [0, 0, 0], 26, 118, { primePower: 130.5, mudPct: 18 }), // jockey: Luis Saez, trainer: Jose F. D'Angelo, post: 2
    h("3", "Final Accord", 6.0, "EP", [82, 87, 0], 180, 122, { primePower: 137.9, earlyPaceLast: 100, latePaceLast: 69, mudPct: 12 }), // jockey: Jose L. Ortiz, trainer: Mark E. Casse, post: 3
    h("4", "Thank You Amy", 30.0, "E", [75, 76, 0], 26, 118, { primePower: 129.1, mudPct: 14 }), // jockey: Sonny Leon, trainer: Ron G. Potts, post: 4
    h("5", "Cy Fair", 2.5, "EP", [96, 0, 0], 19, 122, { primePower: 163.1, earlyPaceLast: 100, latePaceLast: 84, mudPct: 20 }), // jockey: Irad Ortiz Jr., trainer: George Weaver, post: 5
    h("6", "Hen Party", 4.5, "P", [89, 85, 0], 32, 118, { primePower: 138.1, earlyPaceLast: 83, latePaceLast: 96, mudPct: 18 }), // jockey: Flavien Prat, trainer: Eoin G. Harty, post: 6
    h("7", "Midnight Martini", 12.0, "E", [0, 0, 0], 55, 118, { primePower: 129.3, mudPct: 14 }), // jockey: Javier Castellano, trainer: Mark E. Casse, post: 7
    h("8", "Slay the Day", 3.0, "E", [97, 78, 0], 19, 122, { primePower: 147.5, earlyPaceLast: 99, latePaceLast: 86, mudPct: 18 }), // jockey: John R. Velazquez, trainer: Brian A. Lynch, post: 8
    h("9", "Snow Face Princess", 15.0, "P", [83, 85, 90], 19, 118, { primePower: 142.2, earlyPaceLast: 91, latePaceLast: 84, mudPct: 18 }), // jockey: Florent Geroux, trainer: Steven M. Asmussen, post: 9
  ],
};

// ── R12 — MC 50000 6f Dirt $67,000 ──
const race12: StaticRace = {
  raceNumber: 12, postTime: "6:53 PM",
  raceType: "MC 50000", distance: "6f", surface: "Dirt", purse: 67000, condition: "Fast",
  trackBias: {
    surface: "Dirt", distanceLabel: "6.0f",
    speedBiasPct: 85, railBias: "+",
    eIV: 1.45, epIV: 1.6, pIV: 0.65, sIV: 0.35,
    post1to3IV: 1.55, post4to7IV: 1.0, post8plusIV: 0.62,
  },
  horses: [
    h("2", "Hellacious", 20.0, "EP", [73, 71, 73], 40, 125, { primePower: 113.1, earlyPaceLast: 90, latePaceLast: 76, mudPct: 16 }), // jockey: William Antongeorgi III, trainer: Niccolo Troiani, post: 2
    h("3", "Royal Sapphire", 30.0, "E", [74, 0, 0], 159, 113, { primePower: 115.5, earlyPaceLast: 99, latePaceLast: 66, mudPct: 20 }), // jockey: Summer Pauly, trainer: Ed Moger Jr., post: 3
    h("4", "Dark Rye", 15.0, "NA", [0, 0, 0], 0, 118, { mudPct: 15 }), // jockey: Axel Concepcion, trainer: Michelle Lovell, post: 4
    h("5", "Carcar Express", 12.0, "NA", [47, 53, 0], 559, 125, { primePower: 106.6, earlyPaceLast: 94, latePaceLast: 23, mudPct: 17 }), // jockey: Jaime A. Torres, trainer: Joe Sharp, post: 5
    h("6", "Prime Power", 3.5, "E", [68, 65, 75], 32, 125, { primePower: 120.3, earlyPaceLast: 89, latePaceLast: 68, mudPct: 16 }), // jockey: Irad Ortiz Jr., trainer: Steven M. Asmussen, post: 6
    h("7", "Mizzou", 3.0, "E", [67, 84, 72], 19, 125, { primePower: 122.5, earlyPaceLast: 83, latePaceLast: 79, mudPct: 17 }), // jockey: Tyler Gaffalione, trainer: George Weaver, post: 7
    h("8", "Five Wishes", 6.0, "E", [62, 73, 0], 46, 118, { primePower: 120.2, earlyPaceLast: 96, latePaceLast: 42, mudPct: 15 }), // jockey: Brian J. Hernandez Jr., trainer: Chad Summers, post: 8
    h("9", "Barker", 4.5, "E", [79, 69, 80], 19, 125, { primePower: 119.0, earlyPaceLast: 90, latePaceLast: 79, mudPct: 17 }), // jockey: Luis Saez, trainer: Christopher Davis, post: 9
    h("10", "Castle Run", 8.0, "EP", [70, 75, 0], 59, 125, { primePower: 114.6, earlyPaceLast: 95, latePaceLast: 60, mudPct: 12 }), // jockey: Jose L. Ortiz, trainer: Cherie Devaux, post: 10
    h("12", "Boss' Deed", 20.0, "EP", [79, 70, 77], 39, 118, { primePower: 121.0, earlyPaceLast: 90, latePaceLast: 81, mudPct: 14 }), // jockey: Danny Sheehy, trainer: Troy Newton, post: 12
  ],
};

export const CD_2026_04_30: StaticRace[] = [race1, race2, race3, race4, race5, race6, race7, race8, race9, race10, race11, race12];
export const CD_2026_04_30_DATE = "2026-04-30";

// Mark class drop using currentClass vs avgClassLast3 heuristic
for (const r of CD_2026_04_30) {
  for (const horse of r.horses) {
    if (horse.currentClass && horse.avgClassLast3 && horse.currentClass < horse.avgClassLast3) {
      horse.isClassDrop = true;
    }
  }
}
