// Churchill Downs — 2026-05-02
// Generated by scripts/process_card.py from data/cd-2026-05-02/raw-entries.json
// Limited-data mode: ML/post/jockey/trainer scraped, but Beyer/PP/class not available.
// Track bias uses CD spring-meet defaults (cd-context.ts CD_DEFAULT_BIASES).

import type { StaticRace, StaticHorse } from "./static-types";

const h = (
  program: string, name: string, ml: number, style: string,
  beyers: number[], days: number, weight: number,
  extras: Partial<StaticHorse> = {}
): StaticHorse => ({
  program, name, mlOdds: ml, style,
  last3Beyer: beyers, daysSinceLast: days, weight,
  ...extras,
});

// ── R1 — Mdn120k 1ˆMile Dirt $120,000 ──
const race1: StaticRace = {
  raceNumber: 1, postTime: "None",
  raceType: "Mdn120k", distance: "1ˆMile", surface: "Dirt", purse: 120000, condition: "Fast",
  trackBias: {
    surface: "Dirt", distanceLabel: "8.0f",
    speedBiasPct: 62, railBias: "+",
    eIV: 1.1, epIV: 1.2, pIV: 0.9, sIV: 0.8,
    post1to3IV: 1.25, post4to7IV: 1.0, post8plusIV: 0.78,
  },
  horses: [
    h("1", "Bhatia", 15.0, "S", [0, 0, 0], 0, 118, { /* jockey: Luis Saez, trainer: Christopher Davis, post: ? */ }),
    h("2", "Stakeholder", 20.0, "S", [0, 0, 0], 0, 118, { /* jockey: Brian J. Hernandez Jr., trainer: Ian R. Wilkes, post: ? */ }),
    h("3", "Silent Way", 4.0, "E", [0, 0, 0], 0, 125, { /* jockey: Flavien Prat, trainer: Peter Eurton, post: ? */ }),
    h("4", "Ingleborough", 20.0, "NA", [0, 0, 0], 0, 125, { /* jockey: Martin Garcia, trainer: Dale L. Romans, post: ? */ }),
    h("5", "Get Them Roses", 15.0, "NA", [0, 0, 0], 0, 118, { /* jockey: Tyler Gaffalione, trainer: Brendan P. Walsh, post: ? */ }),
    h("6", "Cromwell", 6.0, "P", [0, 0, 0], 0, 125, { /* jockey: Jose L. Ortiz, trainer: Cherie Devaux, post: ? */ }),
    h("7", "Time to Strike", 20.0, "E", [0, 0, 0], 0, 118, { /* jockey: John R. Velazquez, trainer: Mark E. Casse, post: ? */ }),
    h("8", "Bourbon Dream", 5.0, "P", [0, 0, 0], 0, 118, { /* jockey: Mario Gutierrez, trainer: Fausto Gutierrez, post: ? */ }),
    h("9", "Winston Ave", 4.5, "EP", [0, 0, 0], 0, 118, { /* jockey: Juan J. Hernandez, trainer: Bob Baffert, post: ? */ }),
    h("10", "Midnight Playboy", 15.0, "NA", [0, 0, 0], 0, 118, { /* jockey: Junior Alvarado, trainer: Riley Mott, post: ? */ }),
    h("11", "Powershift", 3.0, "P", [0, 0, 0], 0, 118, { /* jockey: Irad Ortiz Jr., trainer: Todd A. Pletcher, post: ? */ }),
  ],
};

// ── R2 — OC 125000n1x 1ˆMile Dirt $127,000 ──
const race2: StaticRace = {
  raceNumber: 2, postTime: "None",
  raceType: "OC 125000n1x", distance: "1ˆMile", surface: "Dirt", purse: 127000, condition: "Fast",
  trackBias: {
    surface: "Dirt", distanceLabel: "8.0f",
    speedBiasPct: 62, railBias: "+",
    eIV: 1.1, epIV: 1.2, pIV: 0.9, sIV: 0.8,
    post1to3IV: 1.25, post4to7IV: 1.0, post8plusIV: 0.78,
  },
  horses: [
    h("1", "Out of the Woods", 6.0, "E", [0, 0, 0], 0, 122, { /* jockey: John R. Velazquez, trainer: Philip Damato, post: ? */ }),
    h("2", "Sovereign Law", 8.0, "S", [0, 0, 0], 0, 120, { /* jockey: Manuel Franco, trainer: Brad H. Cox, post: ? */ }),
    h("3", "Steel", 20.0, "S", [0, 0, 0], 0, 118, { /* jockey: Junior Alvarado, trainer: William I. Mott, post: ? */ }),
    h("4", "Memory", 4.5, "P", [0, 0, 0], 0, 120, { /* jockey: Flavien Prat, trainer: Bob Baffert, post: ? */ }),
    h("5", "Seal Bay", 30.0, "EP", [0, 0, 0], 0, 115, { /* jockey: Summer Pauly, trainer: Ed Moger Jr., post: ? */ }),
    h("6", "Make My Day", 8.0, "E", [0, 0, 0], 0, 120, { /* jockey: Luis Saez, trainer: Todd A. Pletcher, post: ? */ }),
    h("7", "Very Connected", 12.0, "S", [0, 0, 0], 0, 118, { /* jockey: Christopher Elliott, trainer: Kenneth G. Mcpeek, post: ? */ }),
    h("8", "Taptastic", 3.0, "P", [0, 0, 0], 0, 120, { /* jockey: Irad Ortiz Jr., trainer: Steven M. Asmussen, post: ? */ }),
    h("9", "Our Moneyman", 6.0, "P", [0, 0, 0], 0, 120, { /* jockey: Axel Concepcion, trainer: W. Bret Calhoun, post: ? */ }),
    h("10", "J J Grey", 15.0, "EP", [0, 0, 0], 0, 120, { /* jockey: Brian J. Hernandez Jr., trainer: Kenneth G. Mcpeek, post: ? */ }),
    h("11", "Lincoln's Law", 10.0, "EP", [0, 0, 0], 0, 118, { /* jockey: Tyler Gaffalione, trainer: Philip A. Bauer, post: ? */ }),
    h("12", "Spirit of Royal", 30.0, "S", [0, 0, 0], 0, 118, { /* jockey: Cristian A. Torres, trainer: Dallas Stewart, post: ? */ }),
  ],
};

// ── R3 — OC 80000n2x 1Mile Dirt $134,000 ──
const race3: StaticRace = {
  raceNumber: 3, postTime: "None",
  raceType: "OC 80000n2x", distance: "1Mile", surface: "Dirt", purse: 134000, condition: "Fast",
  trackBias: {
    surface: "Dirt", distanceLabel: "8.0f",
    speedBiasPct: 62, railBias: "+",
    eIV: 1.1, epIV: 1.2, pIV: 0.9, sIV: 0.8,
    post1to3IV: 1.25, post4to7IV: 1.0, post8plusIV: 0.78,
  },
  horses: [
    h("1", "Arro Smash", 15.0, "EP", [0, 0, 0], 0, 122, { /* jockey: Gerardo Corrales, trainer: Philip A. Bauer, post: ? */ }),
    h("2", "Vamos Carlitos", 15.0, "EP", [0, 0, 0], 0, 124, { /* jockey: Tyler Gaffalione, trainer: Gregory D. Foley, post: ? */ }),
    h("3", "Special Caliber", 30.0, "EP", [0, 0, 0], 0, 122, { /* jockey: Edgar Morales, trainer: Michel Douaihy, post: ? */ }),
    h("4", "Comport", 15.0, "EP", [0, 0, 0], 0, 116, { /* jockey: Jose L. Ortiz, trainer: Eddie Kenneally, post: ? */ }),
    h("5", "John Hancock", 6.0, "E", [0, 0, 0], 0, 122, { /* jockey: Irad Ortiz Jr., trainer: Brad H. Cox, post: ? */ }),
    h("6", "Who Dey", 4.5, "P", [0, 0, 0], 0, 122, { /* jockey: Brian J. Hernandez Jr., trainer: Thomas Drury Jr., post: ? */ }),
    h("7", "Mitochondria", 30.0, "S", [0, 0, 0], 0, 124, { /* jockey: Mario Gutierrez, trainer: Anthony Stephen, post: ? */ }),
    h("8", "Racing Driver", 20.0, "P", [0, 0, 0], 0, 122, { /* jockey: Luan Machado, trainer: Gustavo Delgado, post: ? */ }),
    h("9", "Keewaydin", 8.0, "E", [0, 0, 0], 0, 122, { /* jockey: Jaime A. Torres, trainer: William Walden, post: ? */ }),
    h("10", "Vibe", 6.0, "EP", [0, 0, 0], 0, 124, { /* jockey: Luis Saez, trainer: Todd A. Pletcher, post: ? */ }),
    h("11", "Aleman", 30.0, "EP", [0, 0, 0], 0, 122, { /* jockey: Danny Sheehy, trainer: Kathy Jarvis, post: ? */ }),
    h("12", "Praetor", 3.0, "E", [0, 0, 0], 0, 122, { /* jockey: Flavien Prat, trainer: Chad C. Brown, post: ? */ }),
    h("13", "Attache", 20.0, "P", [0, 0, 0], 0, 122, { /* jockey: Juan J. Hernandez, trainer: Michael J. Maker, post: ? */ }),
    h("14", "Bullard", 12.0, "P", [0, 0, 0], 0, 122, { /* jockey: John R. Velazquez, trainer: Michael W. Mccarthy, post: ? */ }),
  ],
};

// ── R4 — DctyDst-G1 7Furlongs Dirt $1,000,000 ──
const race4: StaticRace = {
  raceNumber: 4, postTime: "None",
  raceType: "DctyDst-G1", distance: "7Furlongs", surface: "Dirt", purse: 1000000, condition: "Fast",
  trackBias: {
    surface: "Dirt", distanceLabel: "8.0f",
    speedBiasPct: 85, railBias: "+",
    eIV: 1.45, epIV: 1.6, pIV: 0.65, sIV: 0.35,
    post1to3IV: 1.55, post4to7IV: 1.0, post8plusIV: 0.62,
  },
  horses: [
    h("1", "Usha", 4.5, "EP", [0, 0, 0], 0, 123, { /* jockey: Juan J. Hernandez, trainer: Bob Baffert, post: ? */ }),
    h("2", "Haulin Ice", 4.0, "EP", [0, 0, 0], 0, 123, { /* jockey: Francisco Arrieta, trainer: Saffie A. Joseph Jr., post: ? */ }),
    h("3", "Autumn Evening", 20.0, "EP", [0, 0, 0], 0, 123, { /* jockey: Irad Ortiz Jr., trainer: Jose F. D'Angelo, post: ? */ }),
    h("4", "Ways and Means", 1.6, "EP", [0, 0, 0], 0, 123, { /* jockey: Jose L. Ortiz, trainer: Chad C. Brown, post: ? */ }),
    h("5", "Splendora", 2.0, "EP", [0, 0, 0], 0, 123, { /* jockey: Flavien Prat, trainer: Bob Baffert, post: ? */ }),
    h("6", "R Disaster", 6.0, "E", [0, 0, 0], 0, 123, { /* jockey: Tyler Gaffalione, trainer: Saffie A. Joseph Jr., post: ? */ }),
  ],
};

// ── R5 — TurfSprt-G2 5½Furlongs Turf $600,000 ──
const race5: StaticRace = {
  raceNumber: 5, postTime: "None",
  raceType: "TurfSprt-G2", distance: "5½Furlongs", surface: "Turf", purse: 600000, condition: "Fast",
  trackBias: {
    surface: "Turf", distanceLabel: "8.0f",
    speedBiasPct: 55, railBias: "+",
    eIV: 0.55, epIV: 1.6, pIV: 1.2, sIV: 0.65,
    post1to3IV: 1.55, post4to7IV: 0.9, post8plusIV: 0.4,
  },
  horses: [
    h("1", "Wendelssohn", 15.0, "EP", [0, 0, 0], 0, 121, { /* jockey: Brian J. Hernandez Jr., trainer: Chris A. Hartman, post: ? */ }),
    h("2", "Bear River", 30.0, "E", [0, 0, 0], 0, 121, { /* jockey: James Graham, trainer: J. Keith Desormeaux, post: ? */ }),
    h("3", "My Boy Prince", 2.5, "EP", [0, 0, 0], 0, 125, { /* jockey: Jose L. Ortiz, trainer: Mark E. Casse, post: ? */ }),
    h("4", "Full Disclosure", 30.0, "EP", [0, 0, 0], 0, 121, { /* jockey: Adam Beschizza, trainer: Amzadali Jehaludi, post: ? */ }),
    h("5", "Possiblemente", 10.0, "EP", [0, 0, 0], 0, 121, { /* jockey: Manuel Franco, trainer: Joe Sharp, post: ? */ }),
    h("6", "Its Bourbon Thirty", 15.0, "EP", [0, 0, 0], 0, 121, { /* jockey: Luan Machado, trainer: Jeremiah O'Dwyer, post: ? */ }),
    h("7", "Yellow Card", 4.5, "S", [0, 0, 0], 0, 121, { /* jockey: Flavien Prat, trainer: Michael W. Mccarthy, post: ? */ }),
    h("8", "Mondogetsbuckets", 8.0, "P", [0, 0, 0], 0, 121, { /* jockey: Tyler Gaffalione, trainer: Chris M. Block, post: ? */ }),
    h("9", "Litigation", 3.0, "P", [0, 0, 0], 0, 121, { /* jockey: Irad Ortiz Jr., trainer: Brian A. Lynch, post: ? */ }),
    h("10", "Joe Shiesty", 6.0, "EP", [0, 0, 0], 0, 121, { /* jockey: La Cruz Fernando De, trainer: Eric N. Foster, post: ? */ }),
  ],
};

// ── R6 — KnicksGoL200K 1Mile Dirt $200,000 ──
const race6: StaticRace = {
  raceNumber: 6, postTime: "None",
  raceType: "KnicksGoL200K", distance: "1Mile", surface: "Dirt", purse: 200000, condition: "Fast",
  trackBias: {
    surface: "Dirt", distanceLabel: "8.0f",
    speedBiasPct: 62, railBias: "+",
    eIV: 1.1, epIV: 1.2, pIV: 0.9, sIV: 0.8,
    post1to3IV: 1.25, post4to7IV: 1.0, post8plusIV: 0.78,
  },
  horses: [
    h("1", "Brotha Keny", 15.0, "P", [0, 0, 0], 0, 120, { /* jockey: Manuel Franco, trainer: Jose F. D'Angelo, post: ? */ }),
    h("2", "Dragoon Guard", 3.0, "E", [0, 0, 0], 0, 118, { /* jockey: Irad Ortiz Jr., trainer: Brad H. Cox, post: ? */ }),
    h("3", "Banjo Chris", 20.0, "P", [0, 0, 0], 0, 118, { /* jockey: Edgar Morales, trainer: Troy S. Wismer, post: ? */ }),
    h("4", "Be You", 3.5, "P", [0, 0, 0], 0, 118, { /* jockey: John R. Velazquez, trainer: Todd A. Pletcher, post: ? */ }),
    h("5", "Prince of Power", 30.0, "E", [0, 0, 0], 0, 118, { /* jockey: Mario Gutierrez, trainer: Andres Cambray, post: ? */ }),
    h("6", "Tour Player", 4.0, "EP", [0, 0, 0], 0, 123, { /* jockey: Flavien Prat, trainer: D. Whitworth Beckman, post: ? */ }),
    h("7", "Will Take It", 8.0, "P", [0, 0, 0], 0, 123, { /* jockey: Brian J. Hernandez Jr., trainer: Dallas Stewart, post: ? */ }),
    h("8", "Bernin Hot", 30.0, "E", [0, 0, 0], 0, 118, { /* jockey: Ben Curtis, trainer: Rohan G. Crichton, post: ? */ }),
    h("9", "Scotland", 20.0, "P", [0, 0, 0], 0, 118, { /* jockey: Luis Saez, trainer: William I. Mott, post: ? */ }),
    h("10", "Capital Idea", 5.0, "P", [0, 0, 0], 0, 118, { /* jockey: Junior Alvarado, trainer: William I. Mott, post: ? */ }),
    h("11", "Moonlight", 8.0, "S", [0, 0, 0], 0, 120, { /* jockey: Jose L. Ortiz, trainer: Chris M. Block, post: ? */ }),
  ],
};

// ── R7 — DstfTfMl-G2 1Mile Turf $1,000,000 ──
const race7: StaticRace = {
  raceNumber: 7, postTime: "None",
  raceType: "DstfTfMl-G2", distance: "1Mile", surface: "Turf", purse: 1000000, condition: "Fast",
  trackBias: {
    surface: "Turf", distanceLabel: "8.0f",
    speedBiasPct: 45, railBias: "+",
    eIV: 0.55, epIV: 1.35, pIV: 1.25, sIV: 0.85,
    post1to3IV: 1.4, post4to7IV: 0.95, post8plusIV: 0.42,
  },
  horses: [
    h("1", "Italian Soiree", 10.0, "P", [0, 0, 0], 0, 118, { /* jockey: Manuel Franco, trainer: H. Graham Motion, post: ? */ }),
    h("2", "Sweet Rebecca", 2.5, "EP", [0, 0, 0], 0, 118, { /* jockey: Tyler Gaffalione, trainer: Brendan P. Walsh, post: ? */ }),
    h("3", "Portfolio Duration", 4.0, "P", [0, 0, 0], 0, 118, { /* jockey: Flavien Prat, trainer: Chad C. Brown, post: ? */ }),
    h("4", "Temptable", 8.0, "NA", [0, 0, 0], 0, 118, { /* jockey: Junior Alvarado, trainer: William I. Mott, post: ? */ }),
    h("5", "Classic Q", 6.0, "EP", [0, 0, 0], 0, 118, { /* jockey: John R. Velazquez, trainer: Mark E. Casse, post: ? */ }),
    h("6", "Vina Arana", 20.0, "S", [0, 0, 0], 0, 118, { /* jockey: Adam Beschizza, trainer: Jack Sisterson, post: ? */ }),
    h("7", "Movin' On Up", 12.0, "EP", [0, 0, 0], 0, 118, { /* jockey: Jose L. Ortiz, trainer: Saffie A. Joseph Jr., post: ? */ }),
    h("8", "Pin Up Betty", 3.5, "S", [0, 0, 0], 0, 118, { /* jockey: Juan J. Hernandez, trainer: Michael J. Maker, post: ? */ }),
    h("9", "Maggie Go", 8.0, "S", [0, 0, 0], 0, 118, { /* jockey: Irad Ortiz Jr., trainer: Chad C. Brown, post: ? */ }),
  ],
};

// ── R8 — PDayMile-G2 1Mile Dirt $750,000 ──
const race8: StaticRace = {
  raceNumber: 8, postTime: "None",
  raceType: "PDayMile-G2", distance: "1Mile", surface: "Dirt", purse: 750000, condition: "Fast",
  trackBias: {
    surface: "Dirt", distanceLabel: "8.0f",
    speedBiasPct: 62, railBias: "+",
    eIV: 1.1, epIV: 1.2, pIV: 0.9, sIV: 0.8,
    post1to3IV: 1.25, post4to7IV: 1.0, post8plusIV: 0.78,
  },
  horses: [
    h("1", "Englishman", 3.0, "E", [0, 0, 0], 0, 118, { /* jockey: Jose L. Ortiz, trainer: Cherie Devaux, post: ? */ }),
    h("2", "Trouble Calling", 5.0, "EP", [0, 0, 0], 0, 118, { /* jockey: Luis Saez, trainer: Gregory D. Foley, post: ? */ }),
    h("3", "Work", 50.0, "EP", [0, 0, 0], 0, 118, { /* jockey: Edwin A. Maldonado, trainer: Doug F. O'Neill, post: ? */ }),
    h("4", "Secured Freedom", 20.0, "P", [0, 0, 0], 0, 118, { /* jockey: John R. Velazquez, trainer: Tim Yakteen, post: ? */ }),
    h("5", "Stop the Car", 20.0, "EP", [0, 0, 0], 0, 118, { /* jockey: Tyler Gaffalione, trainer: Brendan P. Walsh, post: ? */ }),
    h("6", "Crude Velocity", 2.5, "P", [0, 0, 0], 0, 118, { /* jockey: Florent Geroux, trainer: Bob Baffert, post: ? */ }),
    h("7", "Crown the Buckeye", 6.0, "EP", [0, 0, 0], 0, 118, { /* jockey: Flavien Prat, trainer: Michael J. Maker, post: ? */ }),
    h("8", "Creole Chrome", 8.0, "EP", [0, 0, 0], 0, 118, { /* jockey: Irad Ortiz Jr., trainer: Joe Sharp, post: ? */ }),
    h("9", "Lockstocknpharoah", 20.0, "EP", [0, 0, 0], 0, 118, { /* jockey: Edgar Morales, trainer: Thomas Drury Jr., post: ? */ }),
    h("10", "Great White", 12.0, "EP", [0, 0, 0], 0, 118, { /* jockey: Alex Achard, trainer: John Ennis, post: ? */ }),
    h("11", "One More Freud", 15.0, "EP", [0, 0, 0], 0, 118, { /* jockey: Juan J. Hernandez, trainer: Robert B. Hess Jr., post: ? */ }),
    h("12", "Baytown Dreamer", 50.0, "E", [0, 0, 0], 0, 118, { /* jockey: Danny Sheehy, trainer: Paul Mcentee, post: ? */ }),
  ],
};

// ── R9 — AmerTurf-G1 1ˆMile Turf $1,000,000 ──
const race9: StaticRace = {
  raceNumber: 9, postTime: "None",
  raceType: "AmerTurf-G1", distance: "1ˆMile", surface: "Turf", purse: 1000000, condition: "Fast",
  trackBias: {
    surface: "Turf", distanceLabel: "8.0f",
    speedBiasPct: 45, railBias: "+",
    eIV: 0.55, epIV: 1.35, pIV: 1.25, sIV: 0.85,
    post1to3IV: 1.4, post4to7IV: 0.95, post8plusIV: 0.42,
  },
  horses: [
    h("1", "Street Beast", 15.0, "EP", [0, 0, 0], 0, 122, { /* jockey: Luan Machado, trainer: Ben Colebrook, post: ? */ }),
    h("2", "Let's Be Frank", 30.0, "S", [0, 0, 0], 0, 122, { /* jockey: Manuel Franco, trainer: Michael W. Mccarthy, post: ? */ }),
    h("3", "Blinging It Back", 30.0, "S", [0, 0, 0], 0, 122, { /* jockey: Axel Concepcion, trainer: Mark E. Casse, post: ? */ }),
    h("4", "Stark Contrast", 4.0, "P", [0, 0, 0], 0, 122, { /* jockey: Flavien Prat, trainer: Michael W. Mccarthy, post: ? */ }),
    h("5", "Blackout Time", 10.0, "E", [0, 0, 0], 0, 122, { /* jockey: Luis Saez, trainer: Kenneth G. Mcpeek, post: ? */ }),
    h("6", "Black Hornet", 20.0, "P", [0, 0, 0], 0, 122, { /* jockey: Declan Cannon, trainer: Brendan P. Walsh, post: ? */ }),
    h("7", "Alpyland", 8.0, "EP", [0, 0, 0], 0, 122, { /* jockey: Javier Castellano, trainer: Mark E. Casse, post: ? */ }),
    h("8", "Greenwich Village", 6.0, "EP", [0, 0, 0], 0, 122, { /* jockey: Juan J. Hernandez, trainer: Bob Baffert, post: ? */ }),
    h("9", "Honey Dutch", 12.0, "EP", [0, 0, 0], 0, 122, { /* jockey: Tyler Gaffalione, trainer: D. Whitworth Beckman, post: ? */ }),
    h("10", "Vasy", 10.0, "EP", [0, 0, 0], 0, 122, { /* jockey: John R. Velazquez, trainer: Brendan P. Walsh, post: ? */ }),
    h("11", "Steel Imperium", 30.0, "S", [0, 0, 0], 0, 122, { /* jockey: Jaime A. Torres, trainer: Caio Caramori, post: ? */ }),
    h("12", "Remember Mamba", 4.5, "P", [0, 0, 0], 0, 122, { /* jockey: Jose L. Ortiz, trainer: Cherie Devaux, post: ? */ }),
    h("13", "Thousandsticks", 15.0, "EP", [0, 0, 0], 0, 122, { /* jockey: Joel Rosario, trainer: Brian A. Lynch, post: ? */ }),
    h("14", "Final Score", 8.0, "E", [0, 0, 0], 0, 122, { /* jockey: Irad Ortiz Jr., trainer: Todd A. Pletcher, post: ? */ }),
  ],
};

// ── R10 — CD-G1 7Furlongs Dirt $1,000,000 ──
const race10: StaticRace = {
  raceNumber: 10, postTime: "None",
  raceType: "CD-G1", distance: "7Furlongs", surface: "Dirt", purse: 1000000, condition: "Fast",
  trackBias: {
    surface: "Dirt", distanceLabel: "8.0f",
    speedBiasPct: 85, railBias: "+",
    eIV: 1.45, epIV: 1.6, pIV: 0.65, sIV: 0.35,
    post1to3IV: 1.55, post4to7IV: 1.0, post8plusIV: 0.62,
  },
  horses: [
    h("1", "Disco Time", 6.0, "EP", [0, 0, 0], 0, 123, { /* jockey: John R. Velazquez, trainer: Brad H. Cox, post: ? */ }),
    h("2", "Cornucopian", 3.5, "EP", [0, 0, 0], 0, 123, { /* jockey: Juan J. Hernandez, trainer: Bob Baffert, post: ? */ }),
    h("3", "Macho Music", 30.0, "E", [0, 0, 0], 0, 123, { /* jockey: Javier Castellano, trainer: Rohan G. Crichton, post: ? */ }),
    h("4", "Hall of Fame", 20.0, "P", [0, 0, 0], 0, 123, { /* jockey: Jose L. Ortiz, trainer: Steven M. Asmussen, post: ? */ }),
    h("5", "Disruptor", 8.0, "EP", [0, 0, 0], 0, 123, { /* jockey: Irad Ortiz Jr., trainer: Todd A. Pletcher, post: ? */ }),
    h("6", "Knightsbridge", 1.8, "EP", [0, 0, 0], 0, 123, { /* jockey: Junior Alvarado, trainer: William I. Mott, post: ? */ }),
    h("7", "Imagination", 6.0, "P", [0, 0, 0], 0, 123, { /* jockey: Flavien Prat, trainer: Bob Baffert, post: ? */ }),
    h("8", "T O Elvis", 30.0, "NA", [0, 0, 0], 0, 123, { /* jockey: Ryusei Sakai, trainer: Daisuke Takayanagi, post: ? */ }),
    h("9", "Crazy Mason", 15.0, "S", [0, 0, 0], 0, 123, { /* jockey: Manuel Franco, trainer: Gregory D. Sacco, post: ? */ }),
    h("10", "Banishing", 12.0, "P", [0, 0, 0], 0, 123, { /* jockey: Tyler Gaffalione, trainer: David Jacobson, post: ? */ }),
    h("11", "Point Dume", 15.0, "E", [0, 0, 0], 0, 123, { /* jockey: Edwin Gonzalez, trainer: Timothy C. Kreiser, post: ? */ }),
  ],
};

// ── R11 — TurfClsc-G1 1„Mile(T) 4&up  Turf $1,500,000 ──
const race11: StaticRace = {
  raceNumber: 11, postTime: "None",
  raceType: "TurfClsc-G1 1„Mile(T) 4&up", distance: "", surface: "Turf", purse: 1500000, condition: "Fast",
  trackBias: {
    surface: "Turf", distanceLabel: "8.0f",
    speedBiasPct: 55, railBias: "+",
    eIV: 0.55, epIV: 1.6, pIV: 1.2, sIV: 0.65,
    post1to3IV: 1.55, post4to7IV: 0.9, post8plusIV: 0.4,
  },
  horses: [
    h("1", "Corruption", 15.0, "EP", [0, 0, 0], 0, 123, { /* jockey: John R. Velazquez, trainer: Mark E. Casse, post: ? */ }),
    h("2", "Dashman", 20.0, "EP", [0, 0, 0], 0, 123, { /* jockey: Joel Rosario, trainer: Brian A. Lynch, post: ? */ }),
    h("3", "Asbury Park", 8.0, "S", [0, 0, 0], 0, 123, { /* jockey: Flavien Prat, trainer: Chad C. Brown, post: ? */ }),
    h("4", "Program Trading", 4.0, "P", [0, 0, 0], 0, 123, { /* jockey: Tyler Gaffalione, trainer: Chad C. Brown, post: ? */ }),
    h("5", "Mercante", 12.0, "EP", [0, 0, 0], 0, 123, { /* jockey: Joseph D. Ramos, trainer: Brian Knippenberg, post: ? */ }),
    h("6", "Rhetorical", 2.5, "P", [0, 0, 0], 0, 123, { /* jockey: Irad Ortiz Jr., trainer: William Walden, post: ? */ }),
    h("7", "Gold Phoenix", 10.0, "S", [0, 0, 0], 0, 123, { /* jockey: Hector I. Berrios, trainer: Philip Damato, post: ? */ }),
    h("8", "Astronomer", 30.0, "P", [0, 0, 0], 0, 123, { /* jockey: Javier Castellano, trainer: Simon Callaghan, post: ? */ }),
    h("9", "Test Score", 3.5, "P", [0, 0, 0], 0, 123, { /* jockey: Manuel Franco, trainer: H. Graham Motion, post: ? */ }),
    h("10", "Make Me King", 6.0, "NA", [0, 0, 0], 0, 123, { /* jockey: Jose L. Ortiz, trainer: Jehani H.A. Al, post: ? */ }),
  ],
};

// ── R12 — KyDerby-G1 1‚Mile Dirt $5,000,000 ──
const race12: StaticRace = {
  raceNumber: 12, postTime: "None",
  raceType: "KyDerby-G1", distance: "1‚Mile", surface: "Dirt", purse: 5000000, condition: "Fast",
  trackBias: {
    surface: "Dirt", distanceLabel: "8.0f",
    speedBiasPct: 62, railBias: "+",
    eIV: 1.1, epIV: 1.2, pIV: 0.9, sIV: 0.8,
    post1to3IV: 1.25, post4to7IV: 1.0, post8plusIV: 0.78,
  },
  horses: [
    h("1", "Renegade", 4.0, "S", [0, 0, 0], 0, 126, { /* jockey: Irad Ortiz Jr., trainer: Todd A. Pletcher, post: ? */ }),
    h("2", "Albus", 30.0, "EP", [0, 0, 0], 0, 126, { /* jockey: Manuel Franco, trainer: Riley Mott, post: ? */ }),
    h("3", "Intrepido", 50.0, "EP", [0, 0, 0], 0, 126, { /* jockey: Hector I. Berrios, trainer: Jeff Mullins, post: ? */ }),
    h("4", "Litmus Test", 50.0, "EP", [0, 0, 0], 0, 126, { /* jockey: Martin Garcia, trainer: Bob Baffert, post: ? */ }),
    h("5", "Right to Party", 30.0, "S", [0, 0, 0], 0, 126, { /* jockey: Christopher Elliott, trainer: Kenneth G. Mcpeek, post: ? */ }),
    h("6", "Commandment", 6.0, "P", [0, 0, 0], 0, 126, { /* jockey: Luis Saez, trainer: Brad H. Cox, post: ? */ }),
    h("7", "Danon Bourbon", 20.0, "NA", [0, 0, 0], 0, 126, { /* jockey: Atsuya Nishimura, trainer: Manabu Ikezoe, post: ? */ }),
    h("8", "So Happy", 15.0, "EP", [0, 0, 0], 0, 126, { /* jockey: Mike E. Smith, trainer: Mark Glatt, post: ? */ }),
    h("9", "The Puma", 10.0, "P", [0, 0, 0], 0, 126, { /* jockey: Javier Castellano, trainer: Gustavo Delgado, post: ? */ }),
    h("10", "Wonder Dean", 30.0, "NA", [0, 0, 0], 0, 126, { /* jockey: Ryusei Sakai, trainer: Daisuke Takayanagi, post: ? */ }),
    h("11", "Incredibolt", 20.0, "P", [0, 0, 0], 0, 126, { /* jockey: Jaime A. Torres, trainer: Riley Mott, post: ? */ }),
    h("12", "Chief Wallabee", 8.0, "EP", [0, 0, 0], 0, 126, { /* jockey: Junior Alvarado, trainer: William I. Mott, post: ? */ }),
    h("13", "Silent Tactic", 20.0, "P", [0, 0, 0], 0, 126, { /* jockey: Cristian A. Torres, trainer: Mark E. Casse, post: ? */ }),
    h("14", "Potente", 20.0, "EP", [0, 0, 0], 0, 126, { /* jockey: Juan J. Hernandez, trainer: Bob Baffert, post: ? */ }),
    h("15", "Emerging Market", 15.0, "S", [0, 0, 0], 0, 126, { /* jockey: Flavien Prat, trainer: Chad C. Brown, post: ? */ }),
    h("16", "Pavlovian", 30.0, "EP", [0, 0, 0], 0, 126, { /* jockey: Edwin A. Maldonado, trainer: Doug F. O'Neill, post: ? */ }),
    h("17", "Six Speed", 50.0, "NA", [0, 0, 0], 0, 126, { /* jockey: Brian J. Hernandez Jr., trainer: Bhupat Seemar, post: ? */ }),
    h("18", "Further Ado", 6.0, "P", [0, 0, 0], 0, 126, { /* jockey: John R. Velazquez, trainer: Brad H. Cox, post: ? */ }),
    h("19", "Golden Tempo", 30.0, "S", [0, 0, 0], 0, 126, { /* jockey: Jose L. Ortiz, trainer: Cherie Devaux, post: ? */ }),
    h("20", "Fulleffort", 20.0, "S", [0, 0, 0], 0, 126, { /* jockey: Tyler Gaffalione, trainer: Brad H. Cox, post: ? */ }),
    h("21", "Great White", 50.0, "EP", [0, 0, 0], 0, 126, { /* jockey: Alex Achard, trainer: John Ennis, post: ? */ }),
    h("22", "Ocelli", 50.0, "S", [0, 0, 0], 0, 126, { /* jockey: Joseph D. Ramos, trainer: D. Whitworth Beckman, post: ? */ }),
    h("23", "Robusta", 50.0, "EP", [0, 0, 0], 0, 126, { /* jockey: Emisael Jaramillo, trainer: Doug F. O'Neill, post: ? */ }),
    h("24", "Corona de Oro", 50.0, "EP", [0, 0, 0], 0, 126, { /* jockey: Brian J. Hernandez Jr., trainer: Dallas Stewart, post: ? */ }),
  ],
};

// ── R13 — OC 125000n1x 6½Furlongs Dirt $127,000 ──
const race13: StaticRace = {
  raceNumber: 13, postTime: "None",
  raceType: "OC 125000n1x", distance: "6½Furlongs", surface: "Dirt", purse: 127000, condition: "Fast",
  trackBias: {
    surface: "Dirt", distanceLabel: "8.0f",
    speedBiasPct: 85, railBias: "+",
    eIV: 1.45, epIV: 1.6, pIV: 0.65, sIV: 0.35,
    post1to3IV: 1.55, post4to7IV: 1.0, post8plusIV: 0.62,
  },
  horses: [
    h("1", "Small Town", 8.0, "P", [0, 0, 0], 0, 118, { /* jockey: Flavien Prat, trainer: Michael W. Mccarthy, post: ? */ }),
    h("2", "Heartily", 12.0, "E", [0, 0, 0], 0, 118, { /* jockey: John R. Velazquez, trainer: Wesley A. Ward, post: ? */ }),
    h("3", "Red Lad", 30.0, "E", [0, 0, 0], 0, 118, { /* jockey: Danny Sheehy, trainer: Paul Mcentee, post: ? */ }),
    h("4", "Ring Curl", 15.0, "E", [0, 0, 0], 0, 122, { /* jockey: William Antongeorgi III, trainer: Troy S. Wismer, post: ? */ }),
    h("5", "Hulkamania", 8.0, "P", [0, 0, 0], 0, 118, { /* jockey: Tyler Gaffalione, trainer: D. Whitworth Beckman, post: ? */ }),
    h("6", "Cruisin Chuck", 15.0, "P", [0, 0, 0], 0, 120, { /* jockey: Edgar Morales, trainer: Gregory D. Foley, post: ? */ }),
    h("7", "Sav'n Money", 20.0, "S", [0, 0, 0], 0, 118, { /* jockey: Brian J. Hernandez Jr., trainer: Wayne M. Catalano, post: ? */ }),
    h("8", "Gilded Bandit", 3.0, "P", [0, 0, 0], 0, 122, { /* jockey: Junior Alvarado, trainer: William I. Mott, post: ? */ }),
    h("9", "Thunder Buck", 15.0, "P", [0, 0, 0], 0, 118, { /* jockey: Luis Saez, trainer: Brendan P. Walsh, post: ? */ }),
    h("10", "Buetane", 2.5, "P", [0, 0, 0], 0, 118, { /* jockey: Irad Ortiz Jr., trainer: Bob Baffert, post: ? */ }),
    h("11", "Noble Affair", 4.5, "EP", [0, 0, 0], 0, 118, { /* jockey: Jose L. Ortiz, trainer: Steven M. Asmussen, post: ? */ }),
  ],
};

// ── R14 — Mdn120k 7Furlongs Dirt $120,000 ──
const race14: StaticRace = {
  raceNumber: 14, postTime: "None",
  raceType: "Mdn120k", distance: "7Furlongs", surface: "Dirt", purse: 120000, condition: "Fast",
  trackBias: {
    surface: "Dirt", distanceLabel: "8.0f",
    speedBiasPct: 85, railBias: "+",
    eIV: 1.45, epIV: 1.6, pIV: 0.65, sIV: 0.35,
    post1to3IV: 1.55, post4to7IV: 1.0, post8plusIV: 0.62,
  },
  horses: [
    h("1", "Boylston", 10.0, "NA", [0, 0, 0], 0, 118, { /* jockey: John R. Velazquez, trainer: William Walden, post: ? */ }),
    h("2", "Bestball", 30.0, "S", [0, 0, 0], 0, 124, { /* jockey: James Graham, trainer: Destin G. Heath, post: ? */ }),
    h("3", "Interrogator", 6.0, "NA", [0, 0, 0], 0, 118, { /* jockey: Irad Ortiz Jr., trainer: Steven M. Asmussen, post: ? */ }),
    h("4", "Sleeping Warrior", 15.0, "NA", [0, 0, 0], 0, 124, { /* jockey: Gerardo Corrales, trainer: Philip A. Bauer, post: ? */ }),
    h("5", "Don's Winner", 8.0, "NA", [0, 0, 0], 0, 118, { /* jockey: Jose L. Ortiz, trainer: Joe Sharp, post: ? */ }),
    h("6", "Prize Pick", 12.0, "EP", [0, 0, 0], 0, 118, { /* jockey: Joel Rosario, trainer: Brian A. Lynch, post: ? */ }),
    h("7", "Act Of Parliament", 6.0, "NA", [0, 0, 0], 0, 118, { /* jockey: Luis Saez, trainer: Brad H. Cox, post: ? */ }),
    h("8", "Find No Fault", 4.5, "P", [0, 0, 0], 0, 118, { /* jockey: Tyler Gaffalione, trainer: Dale L. Romans, post: ? */ }),
    h("9", "Big Jake", 8.0, "NA", [0, 0, 0], 0, 118, { /* jockey: Flavien Prat, trainer: Bob Baffert, post: ? */ }),
    h("10", "Chianti Town", 20.0, "EP", [0, 0, 0], 0, 118, { /* jockey: Axel Concepcion, trainer: Dallas Stewart, post: ? */ }),
    h("11", "Great Moment", 12.0, "P", [0, 0, 0], 0, 124, { /* jockey: Edgar Morales, trainer: Gregory D. Foley, post: ? */ }),
    h("12", "Big Braciole", 30.0, "S", [0, 0, 0], 0, 124, { /* jockey: Gabriel Saez, trainer: Kent Knudsen, post: ? */ }),
    h("13", "Noble Anthem", 20.0, "E", [0, 0, 0], 0, 118, { /* jockey: Javier Castellano, trainer: Ron Moquett, post: ? */ }),
    h("14", "Brave Pilot", 8.0, "NA", [0, 0, 0], 0, 118, { /* jockey: Juan J. Hernandez, trainer: Michael W. Mccarthy, post: ? */ }),
  ],
};

export const cd20260502Card: StaticRace[] = [race1, race2, race3, race4, race5, race6, race7, race8, race9, race10, race11, race12, race13, race14];

// Aliases mirroring cd-2026-04-30.ts naming so existing pages can swap import paths only.
export const CD_2026_05_02 = cd20260502Card;
export const CD_2026_05_02_DATE = "2026-05-02";
