// Churchill Downs — 2026-04-25
// Generated by scripts/process_card.py from data/cd-2026-04-25/raw-entries.json
// Limited-data mode: ML/post/jockey/trainer scraped, but Beyer/PP/class not available.
// Track bias uses CD spring-meet defaults (cd-context.ts CD_DEFAULT_BIASES).

import type { StaticRace, StaticHorse } from "./keeneland-apr18";

const h = (
  program: string, name: string, ml: number, style: string,
  beyers: number[], days: number, weight: number,
  extras: Partial<StaticHorse> = {}
): StaticHorse => ({
  program, name, mlOdds: ml, style,
  last3Beyer: beyers, daysSinceLast: days, weight,
  ...extras,
});

// ── R1 — MSW 1 1/4m Dirt $120,000 ──
const race1: StaticRace = {
  raceNumber: 1, postTime: "12:45 PM",
  raceType: "MSW", distance: "1 1/4m", surface: "Dirt", purse: 120000, condition: "Fast",
  trackBias: {
    surface: "Dirt", distanceLabel: "10.0f",
    speedBiasPct: 62, railBias: "+",
    eIV: 1.1, epIV: 1.2, pIV: 0.9, sIV: 0.8,
    post1to3IV: 1.25, post4to7IV: 1.0, post8plusIV: 0.78,
  },
  horses: [
    h("1", "Too Many Mikes", 8.0, "P", [0, 0, 0], 0, 120, { /* jockey: Tyler Gaffalione, trainer: H. Graham Motion, post: 1 */ }),
    h("2", "Island Girl", 6.0, "P", [0, 0, 0], 0, 120, { /* jockey: Luan Machado, trainer: Ben Colebrook, post: 2 */ }),
    h("3", "Ati Girl", 3.0, "P", [0, 0, 0], 0, 120, { /* jockey: Irad Ortiz, Jr., trainer: William I. Mott, post: 3 */ }),
    h("4", "Una Quaedam", 20.0, "P", [0, 0, 0], 0, 120, { /* jockey: Jaime A. Torres, trainer: Eduardo Caramori, post: 4 */ }),
    h("5", "Plaza Cue", 2.0, "P", [0, 0, 0], 0, 120, { /* jockey: Luis Saez, trainer: Kenneth G. McPeek, post: 5 */ }),
    h("6", "Pure Joy", 1.8, "P", [0, 0, 0], 0, 120, { /* jockey: Jose L. Ortiz, trainer: Steven M. Asmussen, post: 6 */ }),
  ],
};

// ── R2 — MSW 4 1/2f Dirt $92,000 ──
const race2: StaticRace = {
  raceNumber: 2, postTime: "1:20 PM",
  raceType: "MSW", distance: "4 1/2f", surface: "Dirt", purse: 92000, condition: "Fast",
  trackBias: {
    surface: "Dirt", distanceLabel: "4.5f",
    speedBiasPct: 85, railBias: "+",
    eIV: 1.45, epIV: 1.6, pIV: 0.65, sIV: 0.35,
    post1to3IV: 1.55, post4to7IV: 1.0, post8plusIV: 0.62,
  },
  horses: [
    h("1", "Sargent Bilko", 3.5, "P", [0, 0, 0], 0, 120, { /* jockey: Jose L. Ortiz, trainer: Eddie Kenneally, post: 1 */ }),
    h("2", "Tio Colocho", 15.0, "P", [0, 0, 0], 0, 120, { /* jockey: Jann N. Hernandez, trainer: Rey Hernandez, post: 2 */ }),
    h("3", "Be My Pal", 4.5, "P", [0, 0, 0], 0, 120, { /* jockey: Jaime A. Torres, trainer: Riley Mott, post: 3 */ }),
    h("4", "Tigrado", 8.0, "P", [0, 0, 0], 0, 120, { /* jockey: Evin A. Roman, trainer: Michel Douaihy, post: 4 */ }),
    h("5", "Happy Away", 1.4, "P", [0, 0, 0], 0, 120, { /* jockey: Irad Ortiz, Jr., trainer: Wesley A. Ward, post: 5 */ }),
    h("6", "Mindful Keeper", 20.0, "P", [0, 0, 0], 0, 120, { /* jockey: Edgar Morales, trainer: Chasey Deville Pomier, post: 6 */ }),
    h("7", "Uncle With Money", 6.0, "P", [0, 0, 0], 0, 120, { /* jockey: Luis Saez, trainer: Rey Hernandez, post: 7 */ }),
    h("8", "Mo Surprises", 10.0, "P", [0, 0, 0], 0, 120, { /* jockey: Danny Sheehy, trainer: John Ennis, post: 8 */ }),
  ],
};

// ── R3 — CLM 30000 1m Dirt $63,000 ──
const race3: StaticRace = {
  raceNumber: 3, postTime: "1:56 PM",
  raceType: "CLM 30000", distance: "1m", surface: "Dirt", purse: 63000, condition: "Fast",
  trackBias: {
    surface: "Dirt", distanceLabel: "8.0f",
    speedBiasPct: 62, railBias: "+",
    eIV: 1.1, epIV: 1.2, pIV: 0.9, sIV: 0.8,
    post1to3IV: 1.25, post4to7IV: 1.0, post8plusIV: 0.78,
  },
  horses: [
    h("1", "Champagne Nights", 8.0, "P", [0, 0, 0], 0, 120, { /* jockey: Joseph D. Ramos, trainer: Claude L. Brownfield III, post: 1 */ }),
    h("2", "Barbratina", 2.0, "P", [0, 0, 0], 0, 120, { /* jockey: Irad Ortiz, Jr., trainer: Joe Sharp, post: 2 */ }),
    h("3", "Lady Orient", 1.2, "P", [0, 0, 0], 0, 120, { /* jockey: Jose L. Ortiz, trainer: Kinnon LaRose, post: 3 */ }),
    h("4", "Mint Driven", 12.0, "P", [0, 0, 0], 0, 120, { /* jockey: Gabriel Saez, trainer: Barry L. King, post: 4 */ }),
    h("5", "Saint Nancy S", 4.5, "P", [0, 0, 0], 0, 120, { /* jockey: Luan Machado, trainer: Kenneth G. McPeek, post: 5 */ }),
    h("6", "Wild Acclaim", 10.0, "P", [0, 0, 0], 0, 120, { /* jockey: Edgar Morales, trainer: Andrew McKeever, post: 6 */ }),
  ],
};

// ── R4 — CLM 12500 6f Dirt $45,000 ──
const race4: StaticRace = {
  raceNumber: 4, postTime: "3:05 PM",
  raceType: "CLM 12500", distance: "6f", surface: "Dirt", purse: 45000, condition: "Fast",
  trackBias: {
    surface: "Dirt", distanceLabel: "6.0f",
    speedBiasPct: 85, railBias: "+",
    eIV: 1.45, epIV: 1.6, pIV: 0.65, sIV: 0.35,
    post1to3IV: 1.55, post4to7IV: 1.0, post8plusIV: 0.62,
  },
  horses: [
    h("1", "Illini", 3.0, "P", [0, 0, 0], 0, 120, { /* jockey: James Graham, trainer: Destin G. Heath, post: 1 */ }),
    h("2", "Bet On Bret", 8.0, "P", [0, 0, 0], 0, 120, { /* jockey: Edgar Morales, trainer: Troy S. Wismer, post: 2 */ }),
    h("3", "Be Here", 10.0, "P", [0, 0, 0], 0, 120, { /* jockey: Danny Sheehy, trainer: Ryan D. Walsh, post: 3 */ }),
    h("4", "Upturned Brim", 4.0, "P", [0, 0, 0], 0, 120, { /* jockey: Axel Concepcion, trainer: J. Keith Desormeaux, post: 4 */ }),
    h("5", "Lord Majesty", 2.5, "P", [0, 0, 0], 0, 120, { /* jockey: Tyler Gaffalione, trainer: David Jacobson, post: 5 */ }),
    h("6", "Ready Pursuit", 15.0, "P", [0, 0, 0], 0, 120, { /* jockey: Evin A. Roman, trainer: Reina E. Gonzalez, post: 6 */ }),
    h("7", "Outlier", 12.0, "P", [0, 0, 0], 0, 120, { /* jockey: Mario Gutierrez, trainer: Rick Hiles, post: 7 */ }),
    h("8", "Hocus", 4.5, "P", [0, 0, 0], 0, 120, { /* jockey: Adam Beschizza, trainer: Michael R. Thompson, post: 8 */ }),
  ],
};

// ── R5 — ALW 6 1/2f Dirt $62,000 ──
const race5: StaticRace = {
  raceNumber: 5, postTime: "3:38 PM",
  raceType: "ALW", distance: "6 1/2f", surface: "Dirt", purse: 62000, condition: "Fast",
  trackBias: {
    surface: "Dirt", distanceLabel: "6.5f",
    speedBiasPct: 85, railBias: "+",
    eIV: 1.45, epIV: 1.6, pIV: 0.65, sIV: 0.35,
    post1to3IV: 1.55, post4to7IV: 1.0, post8plusIV: 0.62,
  },
  horses: [
    h("1", "Wistucky", 1.4, "P", [0, 0, 0], 0, 120, { /* jockey: Luis Saez, trainer: Bobby S. Dibona, post: 1 */ }),
    h("2", "Baytown Bruiser", 3.5, "P", [0, 0, 0], 0, 120, { /* jockey: Tyler Gaffalione, trainer: Barry L. King, post: 2 */ }),
    h("3", "Exploration", 3.0, "P", [0, 0, 0], 0, 120, { /* jockey: Irad Ortiz, Jr., trainer: Richard E. Dutrow, Jr., post: 3 */ }),
    h("4", "Bridge Classic", 6.0, "P", [0, 0, 0], 0, 120, { /* jockey: Adam Beschizza, trainer: Jose M. Camejo, post: 4 */ }),
    h("5", "Michael's Cove", 20.0, "P", [0, 0, 0], 0, 120, { /* jockey: Edgar Morales, trainer: Troy Newton, post: 5 */ }),
    h("6", "Tiger's Legacy", 4.5, "P", [0, 0, 0], 0, 120, { /* jockey: Jose L. Ortiz, trainer: Christopher Davis, post: 6 */ }),
  ],
};

// ── R6 — MCL 12500 6f Dirt $35,000 ──
const race6: StaticRace = {
  raceNumber: 6, postTime: "4:12 PM",
  raceType: "MCL 12500", distance: "6f", surface: "Dirt", purse: 35000, condition: "Fast",
  trackBias: {
    surface: "Dirt", distanceLabel: "6.0f",
    speedBiasPct: 85, railBias: "+",
    eIV: 1.45, epIV: 1.6, pIV: 0.65, sIV: 0.35,
    post1to3IV: 1.55, post4to7IV: 1.0, post8plusIV: 0.62,
  },
  horses: [
    h("1", "Cookie Time", 8.0, "P", [0, 0, 0], 0, 120, { /* jockey: John McKee, trainer: Thomas Drury, Jr., post: 1 */ }),
    h("2", "Blasphemous Rumors", 4.0, "P", [0, 0, 0], 0, 120, { /* jockey: Axel Concepcion, trainer: Albert M. Stall, Jr., post: 2 */ }),
    h("3", "Frosty for Ever", 10.0, "P", [0, 0, 0], 0, 120, { /* jockey: Jaime A. Torres, trainer: Jordan Blair, post: 3 */ }),
    h("4", "Pauline's Angel", 30.0, "P", [0, 0, 0], 0, 120, { /* jockey: Dylan Machado, trainer: Barry L. King, post: 4 */ }),
    h("5", "Muscle Mommy", 20.0, "P", [0, 0, 0], 0, 120, { /* jockey: Constantino Roman, trainer: Guber Gorostieta, post: 5 */ }),
    h("6", "Mariposa Moon", 12.0, "P", [0, 0, 0], 0, 120, { /* jockey: Joseph D. Ramos, trainer: Eric N. Foster, post: 6 */ }),
    h("7", "Cocoa Nimbus", 4.5, "P", [0, 0, 0], 0, 120, { /* jockey: Danny Sheehy, trainer: John Ennis, post: 7 */ }),
    h("8", "Dancewhenyoucan", 5.0, "P", [0, 0, 0], 0, 120, { /* jockey: Mario Gutierrez, trainer: Dallas Stewart, post: 8 */ }),
    h("9", "Dodecahedron", 8.0, "P", [0, 0, 0], 0, 120, { /* jockey: Gabriel Saez, trainer: Jerry Antonuik, post: 9 */ }),
    h("10", "Evalina", 12.0, "P", [0, 0, 0], 0, 120, { /* jockey: Kevin J. Jimenez, trainer: Sal Guerrero, post: 10 */ }),
    h("11", "Velveteen", 6.0, "P", [0, 0, 0], 0, 120, { /* jockey: Micah Meeks, trainer: Brian Williamson, post: 11 */ }),
    h("12", "Ojos Locos", 30.0, "P", [0, 0, 0], 0, 120, { /* jockey: Agustin Gomez, trainer: Cirilo Gorostieta, post: 12 */ }),
    h("13", "Click", 3.5, "P", [0, 0, 0], 0, 120, { /* jockey: Gabriel Saez, trainer: W. Bret Calhoun, post: 13 */ }),
  ],
};

// ── R7 — CLM 40000 1m Turf $78,000 ──
const race7: StaticRace = {
  raceNumber: 7, postTime: "4:44 PM",
  raceType: "CLM 40000", distance: "1m", surface: "Turf", purse: 78000, condition: "Fast",
  trackBias: {
    surface: "Turf", distanceLabel: "8.0f",
    speedBiasPct: 45, railBias: "+",
    eIV: 0.55, epIV: 1.35, pIV: 1.25, sIV: 0.85,
    post1to3IV: 1.4, post4to7IV: 0.95, post8plusIV: 0.42,
  },
  horses: [
    h("1", "Missy Bee", 10.0, "P", [0, 0, 0], 0, 120, { /* jockey: Joseph D. Ramos, trainer: Eric N. Foster, post: 1 */ }),
    h("2", "Sheila's Lion", 6.0, "P", [0, 0, 0], 0, 120, { /* jockey: Axel Concepcion, trainer: J. Keith Desormeaux, post: 2 */ }),
    h("3", "Jill Jitterbug", 8.0, "P", [0, 0, 0], 0, 120, { /* jockey: Danny Sheehy, trainer: Ryan D. Walsh, post: 3 */ }),
    h("4", "Classy'n Connected", 2.0, "P", [0, 0, 0], 0, 120, { /* jockey: Brian Joseph Hernandez, Jr., trainer: Thomas Drury, Jr., post: 4 */ }),
    h("5", "Razzle Red", 12.0, "P", [0, 0, 0], 0, 120, { /* jockey: Yarmarie L. Correa, trainer: Jamie L. Grubbs, post: 5 */ }),
    h("6", "White Lilacs", 20.0, "P", [0, 0, 0], 0, 120, { /* jockey: Constantino Roman, trainer: Felipe Salas, post: 6 */ }),
    h("7", "Goodbetterbest", 4.0, "P", [0, 0, 0], 0, 120, { /* jockey: Tyler Gaffalione, trainer: Brittany A. Vanden Berg, post: 7 */ }),
    h("8", "Lady Blake", 30.0, "P", [0, 0, 0], 0, 120, { /* jockey: Jose Ramos Gutierrez, trainer: James E. Baker, post: 8 */ }),
    h("9", "Dozen Diamonds", 3.0, "P", [0, 0, 0], 0, 120, { /* jockey: Edgar Morales, trainer: Chris A. Hartman, post: 9 */ }),
  ],
};

// ── R8 — CLM 16000 6f Dirt $36,000 ──
const race8: StaticRace = {
  raceNumber: 8, postTime: "5:15 PM",
  raceType: "CLM 16000", distance: "6f", surface: "Dirt", purse: 36000, condition: "Fast",
  trackBias: {
    surface: "Dirt", distanceLabel: "6.0f",
    speedBiasPct: 85, railBias: "+",
    eIV: 1.45, epIV: 1.6, pIV: 0.65, sIV: 0.35,
    post1to3IV: 1.55, post4to7IV: 1.0, post8plusIV: 0.62,
  },
  horses: [
    h("1", "War Munny", 15.0, "P", [0, 0, 0], 0, 120, { /* jockey: Tyler Gaffalione, trainer: Thomas D. Vance, post: 1 */ }),
    h("2", "Guardian", 6.0, "P", [0, 0, 0], 0, 120, { /* jockey: Irad Ortiz, Jr., trainer: Eric N. Foster, post: 2 */ }),
    h("3", "Shadow Coast", 3.5, "P", [0, 0, 0], 0, 120, { /* jockey: Luis Saez, trainer: Rohan G. Crichton, post: 3 */ }),
    h("4", "A Cab On the Rocks", 8.0, "P", [0, 0, 0], 0, 120, { /* jockey: Jaime A. Torres, trainer: Ethan W. West, post: 4 */ }),
    h("5", "Mr. Sensei", 12.0, "P", [0, 0, 0], 0, 120, { /* jockey: Jann N. Hernandez, trainer: Rey Hernandez, post: 5 */ }),
    h("6", "Chi Town Prince", 4.5, "P", [0, 0, 0], 0, 120, { /* jockey: Gerardo Corrales, trainer: Larry Rivelli, post: 6 */ }),
    h("7", "Army Wildcatter", 6.0, "P", [0, 0, 0], 0, 120, { /* jockey: Alex Achard, trainer: John Ennis, post: 7 */ }),
    h("8", "Dewy's Denali", 30.0, "P", [0, 0, 0], 0, 120, { /* jockey: Adam Beschizza, trainer: Reina E. Gonzalez, post: 8 */ }),
    h("9", "Pulgarcito", 20.0, "P", [0, 0, 0], 0, 120, { /* jockey: Luan Machado, trainer: Paulo H. Lobo, post: 9 */ }),
    h("10", "Where Y'at", 5.0, "P", [0, 0, 0], 0, 120, { /* jockey: Axel Concepcion, trainer: Michael A. Tomlinson, post: 10 */ }),
    h("11", "Imperial Ruler", 30.0, "P", [0, 0, 0], 0, 120, { /* jockey: Yarmarie L. Correa, trainer: Ismael Bahena, post: 11 */ }),
    h("12", "Stefan's Title", 15.0, "P", [0, 0, 0], 0, 120, { /* jockey: Jose L. Ortiz, trainer: Helen Pitts, post: 12 */ }),
  ],
};

// ── R9 — Stakes 6f Dirt $200,000 ──
const race9: StaticRace = {
  raceNumber: 9, postTime: "5:46 PM",
  raceType: "Stakes", distance: "6f", surface: "Dirt", purse: 200000, condition: "Fast",
  name: "Roxelana S.",
  trackBias: {
    surface: "Dirt", distanceLabel: "6.0f",
    speedBiasPct: 85, railBias: "+",
    eIV: 1.45, epIV: 1.6, pIV: 0.65, sIV: 0.35,
    post1to3IV: 1.55, post4to7IV: 1.0, post8plusIV: 0.62,
  },
  horses: [
    h("1", "One Magic Philly", 2.5, "P", [0, 0, 0], 0, 120, { /* jockey: Tyler Gaffalione, trainer: Brendan P. Walsh, post: 1 */ }),
    h("2", "Jersey Pearl", 6.0, "P", [0, 0, 0], 0, 120, { /* jockey: Luan Machado, trainer: Darrin Miller, post: 2 */ }),
    h("3", "Mink's Palace", 8.0, "P", [0, 0, 0], 0, 120, { /* jockey: Luis Saez, trainer: Eddie Kenneally, post: 3 */ }),
    h("4", "Lotsandlotsofcandy", 3.5, "P", [0, 0, 0], 0, 120, { /* jockey: Brian Joseph Hernandez, Jr., trainer: Paul J. McGee, post: 4 */ }),
    h("5", "Lucille Ball", 15.0, "P", [0, 0, 0], 0, 120, { /* jockey: Axel Concepcion, trainer: Chris J. Englehart, post: 5 */ }),
    h("6", "Zeitlos", 5.0, "P", [0, 0, 0], 0, 120, { /* jockey: Jose L. Ortiz, trainer: Steven M. Asmussen, post: 6 */ }),
    h("7", "Vincey Girl", 4.5, "P", [0, 0, 0], 0, 120, { /* jockey: Irad Ortiz, Jr., trainer: Jose Francisco D'Angelo, post: 7 */ }),
    h("8", "Asternia", 10.0, "P", [0, 0, 0], 0, 120, { /* jockey: Joel Rosario, trainer: Randy L. Morse, post: 8 */ }),
  ],
};

// ── R10 — ALW 1 1/8m Turf $127,000 ──
const race10: StaticRace = {
  raceNumber: 10, postTime: "6:16 PM",
  raceType: "ALW", distance: "1 1/8m", surface: "Turf", purse: 127000, condition: "Fast",
  trackBias: {
    surface: "Turf", distanceLabel: "9.0f",
    speedBiasPct: 45, railBias: "+",
    eIV: 0.55, epIV: 1.35, pIV: 1.25, sIV: 0.85,
    post1to3IV: 1.4, post4to7IV: 0.95, post8plusIV: 0.42,
  },
  horses: [
    h("1", "The Dover Specter", 20.0, "P", [0, 0, 0], 0, 120, { /* jockey: Adam Beschizza, trainer: Kelsey Danner, post: 1 */ }),
    h("2", "Ashley's Archer", 4.5, "P", [0, 0, 0], 0, 120, { /* jockey: Jose L. Ortiz, trainer: Mark E. Casse, post: 2 */ }),
    h("3", "Without (IRE)", 1.6, "P", [0, 0, 0], 0, 120, { /* jockey: Irad Ortiz, Jr., trainer: H. Graham Motion, post: 3 */ }),
    h("4", "Ramblin", 30.0, "P", [0, 0, 0], 0, 120, { /* jockey: Mario Gutierrez, trainer: Bobby C. Barnett, post: 4 */ }),
    h("5", "Seven Wonders", 6.0, "P", [0, 0, 0], 0, 120, { /* jockey: Joel Rosario, trainer: Peter Eurton, post: 5 */ }),
    h("6", "Fort Thomas", 8.0, "P", [0, 0, 0], 0, 120, { /* jockey: Axel Concepcion, trainer: George R. Arnold II, post: 6 */ }),
    h("7", "Theodore George", 12.0, "P", [0, 0, 0], 0, 120, { /* jockey: Danny Sheehy, trainer: Michael W. McCarthy, post: 7 */ }),
    h("8", "Treaty of Rome", 4.0, "P", [0, 0, 0], 0, 120, { /* jockey: Tyler Gaffalione, trainer: Chad C. Brown, post: 8 */ }),
    h("9", "Curlin's Gesture", 20.0, "P", [0, 0, 0], 0, 120, { /* jockey: Gerardo Corrales, trainer: David Jacobson, post: 9 */ }),
    h("10", "Telescopic", 15.0, "P", [0, 0, 0], 0, 120, { /* jockey: Luis Saez, trainer: Victoria H. Oliver, post: 10 */ }),
  ],
};

export const cd20260425Card: StaticRace[] = [race1, race2, race3, race4, race5, race6, race7, race8, race9, race10];
