// Churchill Downs — 2026-04-26
// Generated by scripts/process_card.py from data/cd-2026-04-26/raw-entries.json
// Limited-data mode: ML/post/jockey/trainer scraped, but Beyer/PP/class not available.
// Track bias uses CD spring-meet defaults (cd-context.ts CD_DEFAULT_BIASES).

import type { StaticRace, StaticHorse } from "./static-types";

const h = (
  program: string, name: string, ml: number, style: string,
  beyers: number[], days: number, weight: number,
  extras: Partial<StaticHorse> = {}
): StaticHorse => ({
  program, name, mlOdds: ml, style,
  last3Beyer: beyers, daysSinceLast: days, weight,
  ...extras,
});

// ── R1 — Starter Allowance 1 1/16M Dirt $83,000 ──
const race1: StaticRace = {
  raceNumber: 1, postTime: "12:45 PM",
  raceType: "Starter Allowance", distance: "1 1/16M", surface: "Dirt", purse: 83000, condition: "Fast",
  trackBias: {
    surface: "Dirt", distanceLabel: "8.0f",
    speedBiasPct: 62, railBias: "+",
    eIV: 1.1, epIV: 1.2, pIV: 0.9, sIV: 0.8,
    post1to3IV: 1.25, post4to7IV: 1.0, post8plusIV: 0.78,
  },
  horses: [
    h("1", "C McGriff", 6.0, "P", [0, 0, 0], 0, 120, { /* jockey: Joel Rosario, trainer: Robert Medina, post: 1 */ }),
    h("2", "Bourbon Flight", 5.0, "P", [0, 0, 0], 0, 120, { /* jockey: Irad Ortiz, Jr., trainer: Ian R. Wilkes, post: 2 */ }),
    h("3", "Different Gravy", 4.5, "P", [0, 0, 0], 0, 120, { /* jockey: Ben Curtis, trainer: Eddie Kenneally, post: 3 */ }),
    h("4", "Midway Munny", 10.0, "P", [0, 0, 0], 0, 120, { /* jockey: Alberto Burgos, trainer: Paulo H. Lobo, post: 4 */ }),
    h("5", "Nogradi", 1.8, "P", [0, 0, 0], 0, 120, { /* jockey: Jose L. Ortiz, trainer: Keri Brion, post: 5 */ }),
    h("6", "Cant Stop Munnings", 3.5, "P", [0, 0, 0], 0, 120, { /* jockey: Tyler Gaffalione, trainer: Saffie A. Joseph, Jr., post: 6 */ }),
    h("7", "Six String Prince", 8.0, "P", [0, 0, 0], 0, 120, { /* jockey: Luis Saez, trainer: Ron Moquett, post: 7 */ }),
  ],
};

// ── R2 — MSW 4 1/2F Dirt $92,000 ──
const race2: StaticRace = {
  raceNumber: 2, postTime: "1:14 PM",
  raceType: "MSW", distance: "4 1/2F", surface: "Dirt", purse: 92000, condition: "Fast",
  trackBias: {
    surface: "Dirt", distanceLabel: "8.0f",
    speedBiasPct: 85, railBias: "+",
    eIV: 1.45, epIV: 1.6, pIV: 0.65, sIV: 0.35,
    post1to3IV: 1.55, post4to7IV: 1.0, post8plusIV: 0.62,
  },
  horses: [
    h("1", "Respected Mind", 20.0, "P", [0, 0, 0], 0, 120, { /* jockey: Edgar Morales, trainer: Chasey Deville Pomier, post: 1 */ }),
    h("2", "Storm Diva", 8.0, "P", [0, 0, 0], 0, 120, { /* jockey: Jose L. Ortiz, trainer: Mark E. Casse, post: 2 */ }),
    h("3", "Rebelka", 20.0, "P", [0, 0, 0], 0, 120, { /* jockey: Guillermo Rodriguez, trainer: James K. Chapman, post: 3 */ }),
    h("4", "Youhadme At Merlot", 12.0, "P", [0, 0, 0], 0, 120, { /* jockey: Alex Achard, trainer: John Ennis, post: 4 */ }),
    h("5", "Go New York Go", 4.5, "P", [0, 0, 0], 0, 120, { /* jockey: Luis Saez, trainer: Chad Summers, post: 5 */ }),
    h("6", "Valkyrie", 5.0, "P", [0, 0, 0], 0, 120, { /* jockey: Declan Cannon, trainer: Kenneth G. McPeek, post: 6 */ }),
    h("7", "Cardio Cat", 3.0, "P", [0, 0, 0], 0, 120, { /* jockey: Irad Ortiz, Jr., trainer: Steven M. Asmussen, post: 7 */ }),
    h("8", "She's Toasty", 4.0, "P", [0, 0, 0], 0, 120, { /* jockey: Ben Curtis, trainer: Eddie Kenneally, post: 8 */ }),
    h("9", "Lady Lux", 6.0, "P", [0, 0, 0], 0, 120, { /* jockey: Victor R. Carrasco, trainer: Genaro Garcia, post: 9 */ }),
    h("10", "Powerful Rose", 30.0, "P", [0, 0, 0], 0, 120, { /* jockey: Adam Beschizza, trainer: Chasey Deville Pomier, post: 10 */ }),
    h("11", "Angel Life", 30.0, "P", [0, 0, 0], 0, 120, { /* jockey: Agustin Gomez, trainer: Cirilo Gorostieta, post: 11 */ }),
  ],
};

// ── R3 — MCL 6 1/2F Dirt $48,000 ──
const race3: StaticRace = {
  raceNumber: 3, postTime: "1:43 PM",
  raceType: "MCL", distance: "6 1/2F", surface: "Dirt", purse: 48000, condition: "Fast",
  trackBias: {
    surface: "Dirt", distanceLabel: "8.0f",
    speedBiasPct: 85, railBias: "+",
    eIV: 1.45, epIV: 1.6, pIV: 0.65, sIV: 0.35,
    post1to3IV: 1.55, post4to7IV: 1.0, post8plusIV: 0.62,
  },
  horses: [
    h("1", "Juanita Mychiquita", 4.0, "P", [0, 0, 0], 0, 120, { /* jockey: Edgar Morales, trainer: Genaro Garcia, post: 1 */ }),
    h("2", "Rocky World", 10.0, "P", [0, 0, 0], 0, 120, { /* jockey: Summer Pauly, trainer: Ed Moger, Jr., post: 2 */ }),
    h("3", "Baby Hello", 12.0, "P", [0, 0, 0], 0, 120, { /* jockey: Declan Cannon, trainer: Brian Williamson, post: 3 */ }),
    h("4", "Betty Who", 15.0, "P", [0, 0, 0], 0, 120, { /* jockey: Rafael Bejarano, trainer: Ramon Salcedo, post: 4 */ }),
    h("5", "Ladies Love Cash", 20.0, "P", [0, 0, 0], 0, 120, { /* jockey: Oscar Villarreal, trainer: Yoni R. Orantes, post: 5 */ }),
    h("6", "High Grace", 15.0, "P", [0, 0, 0], 0, 120, { /* jockey: Chase Miller, trainer: Darrin Miller, post: 6 */ }),
    h("7", "Gladly", 5.0, "P", [0, 0, 0], 0, 120, { /* jockey: Jaime A. Torres, trainer: Caio Caramori, post: 7 */ }),
    h("8", "Will Believe", 4.5, "P", [0, 0, 0], 0, 120, { /* jockey: Irving Moncada, trainer: Michael E. Lauer, post: 8 */ }),
    h("9", "Flashy Aviator", 6.0, "P", [0, 0, 0], 0, 120, { /* jockey: Ben Curtis, trainer: Rohan G. Crichton, post: 9 */ }),
    h("10", "State Charmer", 3.0, "P", [0, 0, 0], 0, 120, { /* jockey: Luis Saez, trainer: Timothy E. Hamm, post: 10 */ }),
  ],
};

// ── R4 — CLM 7F Dirt $78,000 ──
const race4: StaticRace = {
  raceNumber: 4, postTime: "2:14 PM",
  raceType: "CLM", distance: "7F", surface: "Dirt", purse: 78000, condition: "Fast",
  trackBias: {
    surface: "Dirt", distanceLabel: "8.0f",
    speedBiasPct: 85, railBias: "+",
    eIV: 1.45, epIV: 1.6, pIV: 0.65, sIV: 0.35,
    post1to3IV: 1.55, post4to7IV: 1.0, post8plusIV: 0.62,
  },
  horses: [
    h("1", "Nuck Chorris", 5.0, "P", [0, 0, 0], 0, 120, { /* jockey: Tyler Gaffalione, trainer: Michael J. Maker, post: 1 */ }),
    h("2", "Versed", 15.0, "P", [0, 0, 0], 0, 120, { /* jockey: Edgar Morales, trainer: Claude L. Brownfield III, post: 2 */ }),
    h("3", "Coal Fired", 20.0, "P", [0, 0, 0], 0, 120, { /* jockey: Gabriel Saez, trainer: Eric N. Foster, post: 3 */ }),
    h("4", "Perfect Audible", 10.0, "P", [0, 0, 0], 0, 120, { /* jockey: Jose L. Ortiz, trainer: Steven M. Asmussen, post: 4 */ }),
    h("5", "Mischief Mania", 3.5, "P", [0, 0, 0], 0, 120, { /* jockey: Irad Ortiz, Jr., trainer: Ed Moger, Jr., post: 5 */ }),
    h("6", "Sonic Surge", 8.0, "P", [0, 0, 0], 0, 120, { /* jockey: Luis Saez, trainer: Bobby S. Dibona, post: 6 */ }),
    h("7", "Kid Twist", 4.5, "P", [0, 0, 0], 0, 120, { /* jockey: Adam Beschizza, trainer: John Ennis, post: 7 */ }),
    h("8", "Epic Summer", 1.6, "P", [0, 0, 0], 0, 120, { /* jockey: Joel Rosario, trainer: George Weaver, post: 8 */ }),
  ],
};

// ── R5 — MCL 6F Dirt $35,000 ──
const race5: StaticRace = {
  raceNumber: 5, postTime: "2:47 PM",
  raceType: "MCL", distance: "6F", surface: "Dirt", purse: 35000, condition: "Fast",
  trackBias: {
    surface: "Dirt", distanceLabel: "8.0f",
    speedBiasPct: 85, railBias: "+",
    eIV: 1.45, epIV: 1.6, pIV: 0.65, sIV: 0.35,
    post1to3IV: 1.55, post4to7IV: 1.0, post8plusIV: 0.62,
  },
  horses: [
    h("1", "Dress Good", 30.0, "P", [0, 0, 0], 0, 120, { /* jockey: Agustin Gomez, trainer: Cirilo Gorostieta, post: 1 */ }),
    h("2", "Richeztoo", 8.0, "P", [0, 0, 0], 0, 120, { /* jockey: Evin A. Roman, trainer: Joel Zawitz, post: 2 */ }),
    h("3", "Calling On Heaven", 1.4, "P", [0, 0, 0], 0, 120, { /* jockey: Tyler Gaffalione, trainer: Michael J. Maker, post: 3 */ }),
    h("4", "Orville's Map", 20.0, "P", [0, 0, 0], 0, 120, { /* jockey: Axel Concepcion, trainer: Dallas Stewart, post: 4 */ }),
    h("5", "Big Nelson", 30.0, "P", [0, 0, 0], 0, 120, { /* jockey: Dylan Machado, trainer: Barry L. King, post: 5 */ }),
    h("6", "Impavido", 3.5, "P", [0, 0, 0], 0, 120, { /* jockey: Luis Saez, trainer: Albert M. Stall, Jr., post: 6 */ }),
    h("7", "Next Time", 4.5, "P", [0, 0, 0], 0, 120, { /* jockey: Gerardo Corrales, trainer: David Jacobson, post: 7 */ }),
    h("8", "Blazing", 15.0, "P", [0, 0, 0], 0, 120, { /* jockey: Danny Sheehy, trainer: Michelle Lovell, post: 8 */ }),
    h("9", "Cause Ima Boss", 30.0, "P", [0, 0, 0], 0, 120, { /* jockey: Constantino Roman, trainer: Guber Gorostieta, post: 9 */ }),
    h("10", "Grab the Spark", 6.0, "P", [0, 0, 0], 0, 120, { /* jockey: Irad Ortiz, Jr., trainer: Ron Moquett, post: 10 */ }),
  ],
};

// ── R6 — AOC 5 1/2F Turf $141,000 ──
const race6: StaticRace = {
  raceNumber: 6, postTime: "3:20 PM",
  raceType: "AOC", distance: "5 1/2F", surface: "Turf", purse: 141000, condition: "Fast",
  trackBias: {
    surface: "Turf", distanceLabel: "8.0f",
    speedBiasPct: 55, railBias: "+",
    eIV: 0.55, epIV: 1.6, pIV: 1.2, sIV: 0.65,
    post1to3IV: 1.55, post4to7IV: 0.9, post8plusIV: 0.4,
  },
  horses: [
    h("1", "Golden Afternoon", 4.5, "P", [0, 0, 0], 0, 120, { /* jockey: Irad Ortiz, Jr., trainer: Nicholas Vaccarezza, post: 1 */ }),
    h("2", "Autodrive", 4.0, "P", [0, 0, 0], 0, 120, { /* jockey: Brian Joseph Hernandez, Jr., trainer: W. Bret Calhoun, post: 2 */ }),
    h("3", "Run Curtis Run", 3.0, "P", [0, 0, 0], 0, 120, { /* jockey: Tyler Gaffalione, trainer: Michael J. Maker, post: 3 */ }),
    h("4", "Amoudi Bay", 5.0, "P", [0, 0, 0], 0, 120, { /* jockey: James Graham, trainer: Lindsay Schultz, post: 4 */ }),
    h("5", "Alder", 15.0, "P", [0, 0, 0], 0, 120, { /* jockey: Gerardo Corrales, trainer: David Jacobson, post: 5 */ }),
    h("6", "T Kraft", 10.0, "P", [0, 0, 0], 0, 120, { /* jockey: Junior Alvarado, trainer: William I. Mott, post: 6 */ }),
    h("7", "Sine Qua Non", 8.0, "P", [0, 0, 0], 0, 120, { /* jockey: Luis Saez, trainer: James P. DiVito, post: 7 */ }),
    h("8", "Step Forward", 3.5, "P", [0, 0, 0], 0, 120, { /* jockey: Joel Rosario, trainer: Michael J. Maker, post: 8 */ }),
  ],
};

// ── R7 — CLM 6F Dirt $36,000 ──
const race7: StaticRace = {
  raceNumber: 7, postTime: "3:51 PM",
  raceType: "CLM", distance: "6F", surface: "Dirt", purse: 36000, condition: "Fast",
  trackBias: {
    surface: "Dirt", distanceLabel: "8.0f",
    speedBiasPct: 85, railBias: "+",
    eIV: 1.45, epIV: 1.6, pIV: 0.65, sIV: 0.35,
    post1to3IV: 1.55, post4to7IV: 1.0, post8plusIV: 0.62,
  },
  horses: [
    h("1", "Zafyre", 30.0, "P", [0, 0, 0], 0, 120, { /* jockey: Gabriel Lagunes, trainer: Jerry Antonuik, post: 1 */ }),
    h("2", "I'm a Cookie Lover", 15.0, "P", [0, 0, 0], 0, 120, { /* jockey: Ben Curtis, trainer: Lacy Pierce, post: 2 */ }),
    h("3", "Ride the Broom", 3.5, "P", [0, 0, 0], 0, 120, { /* jockey: Adam Beschizza, trainer: Joe Blair Roberts, post: 3 */ }),
    h("4", "Sweet Bebsi", 1.6, "P", [0, 0, 0], 0, 120, { /* jockey: Irad Ortiz, Jr., trainer: Rodolphe Brisset, post: 4 */ }),
    h("5", "Mo Indian Lady", 12.0, "P", [0, 0, 0], 0, 120, { /* jockey: Gabriel Saez, trainer: Eric N. Foster, post: 5 */ }),
    h("6", "B D's Angel", 20.0, "P", [0, 0, 0], 0, 120, { /* jockey: Chase Miller, trainer: William E. Duvall, post: 6 */ }),
    h("7", "Sound the Siren", 20.0, "P", [0, 0, 0], 0, 120, { /* jockey: Jose Ramos Gutierrez, trainer: Michael E. Lauer, post: 7 */ }),
    h("8", "Mamarsha", 15.0, "P", [0, 0, 0], 0, 120, { /* jockey: Constantino Roman, trainer: Hutch Holsapple, post: 8 */ }),
    h("9", "Loving Mischief", 4.5, "P", [0, 0, 0], 0, 120, { /* jockey: Edgar Morales, trainer: Genaro Garcia, post: 9 */ }),
    h("10", "Waffle House Gang", 6.0, "P", [0, 0, 0], 0, 120, { /* jockey: Gerardo Corrales, trainer: Keith Kinmon, post: 10 */ }),
  ],
};

// ── R8 — MSW 1 1/4M Dirt $120,000 ──
const race8: StaticRace = {
  raceNumber: 8, postTime: "4:24 PM",
  raceType: "MSW", distance: "1 1/4M", surface: "Dirt", purse: 120000, condition: "Fast",
  trackBias: {
    surface: "Dirt", distanceLabel: "8.0f",
    speedBiasPct: 62, railBias: "+",
    eIV: 1.1, epIV: 1.2, pIV: 0.9, sIV: 0.8,
    post1to3IV: 1.25, post4to7IV: 1.0, post8plusIV: 0.78,
  },
  horses: [
    h("1", "King of Heat", 6.0, "P", [0, 0, 0], 0, 120, { /* jockey: James Graham, trainer: J. Keith Desormeaux, post: 1 */ }),
    h("2", "Stompin Grapes", 1.8, "P", [0, 0, 0], 0, 120, { /* jockey: Brian Joseph Hernandez, Jr., trainer: Ian R. Wilkes, post: 2 */ }),
    h("3", "Tiernanogue", 3.5, "P", [0, 0, 0], 0, 120, { /* jockey: Tyler Gaffalione, trainer: Brendan P. Walsh, post: 3 */ }),
    h("4", "Still Sober", 20.0, "P", [0, 0, 0], 0, 120, { /* jockey: Jaime A. Torres, trainer: Eduardo Caramori, post: 4 */ }),
    h("5", "In America", 30.0, "P", [0, 0, 0], 0, 120, { /* jockey: Joseph D. Ramos, trainer: Fergus Bogle, post: 5 */ }),
    h("6", "Sartorial", 8.0, "P", [0, 0, 0], 0, 120, { /* jockey: Edgar Morales, trainer: George R. Arnold II, post: 6 */ }),
    h("7", "Prayer", 20.0, "P", [0, 0, 0], 0, 120, { /* jockey: Victor R. Carrasco, trainer: George R. Arnold II, post: 7 */ }),
    h("8", "Direct Strike", 4.5, "P", [0, 0, 0], 0, 120, { /* jockey: Irad Ortiz, Jr., trainer: Brad H. Cox, post: 8 */ }),
    h("9", "Silver Shot", 6.0, "P", [0, 0, 0], 0, 120, { /* jockey: Jose L. Ortiz, trainer: Steven M. Asmussen, post: 9 */ }),
  ],
};

// ── R9 — ALW 1 1/16M Turf $127,000 ──
const race9: StaticRace = {
  raceNumber: 9, postTime: "4:56 PM",
  raceType: "ALW", distance: "1 1/16M", surface: "Turf", purse: 127000, condition: "Fast",
  trackBias: {
    surface: "Turf", distanceLabel: "8.0f",
    speedBiasPct: 45, railBias: "+",
    eIV: 0.55, epIV: 1.35, pIV: 1.25, sIV: 0.85,
    post1to3IV: 1.4, post4to7IV: 0.95, post8plusIV: 0.42,
  },
  horses: [
    h("1", "Midway Memories", 4.0, "P", [0, 0, 0], 0, 120, { /* jockey: Irad Ortiz, Jr., trainer: Chad C. Brown, post: 1 */ }),
    h("2", "Humbled", 12.0, "P", [0, 0, 0], 0, 120, { /* jockey: Vincent Cheminaud, trainer: Robert Medina, post: 2 */ }),
    h("3", "Brilliantly", 3.0, "P", [0, 0, 0], 0, 120, { /* jockey: Joel Rosario, trainer: Bob Baffert, post: 3 */ }),
    h("4", "Olivia Valentina", 10.0, "P", [0, 0, 0], 0, 120, { /* jockey: Junior Alvarado, trainer: Carlos Luis Perez, post: 4 */ }),
    h("5", "Snipsnippitysnip", 4.5, "P", [0, 0, 0], 0, 120, { /* jockey: Tyler Gaffalione, trainer: Brendan P. Walsh, post: 5 */ }),
    h("6", "Red Beretta", 50.0, "P", [0, 0, 0], 0, 120, { /* jockey: Evin A. Roman, trainer: Michel Douaihy, post: 6 */ }),
    h("7", "Plaza Athenee (GB)", 8.0, "P", [0, 0, 0], 0, 120, { /* jockey: Ben Curtis, trainer: Brendan P. Walsh, post: 7 */ }),
    h("8", "Salty Senorita", 20.0, "P", [0, 0, 0], 0, 120, { /* jockey: Jaime A. Torres, trainer: Michael J. Maker, post: 8 */ }),
    h("9", "Faithful Departed", 5.0, "P", [0, 0, 0], 0, 120, { /* jockey: Jose L. Ortiz, trainer: Grant T. Forster, post: 9 */ }),
    h("10", "Totally Justified", 6.0, "P", [0, 0, 0], 0, 120, { /* jockey: Danny Sheehy, trainer: Anna M. Meah, post: 10 */ }),
    h("AE11", "French Mistress (AE)", 30.0, "P", [0, 0, 0], 0, 120, { /* jockey: Corey J. Lanerie, trainer: Jeff A. Hiles, post: None */ }),
  ],
};

export const cd20260426Card: StaticRace[] = [race1, race2, race3, race4, race5, race6, race7, race8, race9];
