// Churchill Downs — 2026-04-29
// Generated by scripts/process_card.py from data/cd-2026-04-29/raw-entries.json
// Limited-data mode: ML/post/jockey/trainer scraped, but Beyer/PP/class not available.
// Track bias uses CD spring-meet defaults (cd-context.ts CD_DEFAULT_BIASES).

import type { StaticRace, StaticHorse } from "./keeneland-apr18";

const h = (
  program: string, name: string, ml: number, style: string,
  beyers: number[], days: number, weight: number,
  extras: Partial<StaticHorse> = {}
): StaticHorse => ({
  program, name, mlOdds: ml, style,
  last3Beyer: beyers, daysSinceLast: days, weight,
  ...extras,
});

// ── R1 — CLM 16000 1m Dirt $55,000 ──
const race1: StaticRace = {
  raceNumber: 1, postTime: "12:45 PM",
  raceType: "CLM 16000", distance: "1m", surface: "Dirt", purse: 55000, condition: "Fast",
  trackBias: {
    surface: "Dirt", distanceLabel: "8.0f",
    speedBiasPct: 62, railBias: "+",
    eIV: 1.1, epIV: 1.2, pIV: 0.9, sIV: 0.8,
    post1to3IV: 1.25, post4to7IV: 1.0, post8plusIV: 0.78,
  },
  horses: [
    h("1", "Empire Builder", 2.5, "P", [0, 0, 0], 0, 120, { /* jockey: Tyler Gaffalione, trainer: Armando Hernandez, post: 1 */ }),
    h("2", "Nip N Tuck", 15.0, "P", [0, 0, 0], 0, 120, { /* jockey: Luan Machado, trainer: Barry L. King, post: 2 */ }),
    h("3", "Charbon", 10.0, "P", [0, 0, 0], 0, 120, { /* jockey: Edgar Morales, trainer: Chasey Deville Pomier, post: 3 */ }),
    h("4", "My Noble Knight", 3.0, "P", [0, 0, 0], 0, 120, { /* jockey: Jose L. Ortiz, trainer: Kinnon LaRose, post: 4 */ }),
    h("5", "Tres Soles", 8.0, "P", [0, 0, 0], 0, 120, { /* jockey: Gabriel Saez, trainer: William Stinson, Jr., post: 5 */ }),
    h("6", "Raising Kane", 15.0, "P", [0, 0, 0], 0, 120, { /* jockey: Corey J. Lanerie, trainer: J. Keith Desormeaux, post: 6 */ }),
    h("7", "Quokka", 6.0, "P", [0, 0, 0], 0, 120, { /* jockey: Agustin Gomez, trainer: Cirilo Gorostieta, post: 7 */ }),
    h("8", "National Eclipse", 3.5, "P", [0, 0, 0], 0, 120, { /* jockey: Irad Ortiz, Jr., trainer: Robertino Diodoro, post: 8 */ }),
  ],
};

// ── R2 — CLM 25000 6 1/2f Dirt $64,000 ──
const race2: StaticRace = {
  raceNumber: 2, postTime: "1:15 PM",
  raceType: "CLM 25000", distance: "6 1/2f", surface: "Dirt", purse: 64000, condition: "Fast",
  trackBias: {
    surface: "Dirt", distanceLabel: "6.5f",
    speedBiasPct: 85, railBias: "+",
    eIV: 1.45, epIV: 1.6, pIV: 0.65, sIV: 0.35,
    post1to3IV: 1.55, post4to7IV: 1.0, post8plusIV: 0.62,
  },
  horses: [
    h("1", "Barksdale", 3.0, "P", [0, 0, 0], 0, 120, { /* jockey: Tyler Gaffalione, trainer: David Jacobson, post: 1 */ }),
    h("2", "Chiringo", 10.0, "P", [0, 0, 0], 0, 120, { /* jockey: Edgar Morales, trainer: Genaro Garcia, post: 2 */ }),
    h("3", "Altobelli", 20.0, "P", [0, 0, 0], 0, 120, { /* jockey: Cesar Diaz, trainer: Nery Alvarez, post: 3 */ }),
    h("4", "Real Macho", 3.5, "P", [0, 0, 0], 0, 120, { /* jockey: Micah J. Husbands, trainer: Rohan G. Crichton, post: 4 */ }),
    h("5", "Highly Flammable", 1.8, "P", [0, 0, 0], 0, 120, { /* jockey: Irad Ortiz, Jr., trainer: Joe Sharp, post: 5 */ }),
    h("6", "Mister Mmmmm", 3.0, "P", [0, 0, 0], 0, 120, { /* jockey: Jose L. Ortiz, trainer: Joe Sharp, post: 6 */ }),
    h("7", "Charbonnay", 20.0, "P", [0, 0, 0], 0, 120, { /* jockey: Cesar Orantes, trainer: Nery Alvarez, post: 7 */ }),
  ],
};

// ── R3 — MSW 4 1/2f Dirt $120,000 ──
const race3: StaticRace = {
  raceNumber: 3, postTime: "1:45 PM",
  raceType: "MSW", distance: "4 1/2f", surface: "Dirt", purse: 120000, condition: "Fast",
  trackBias: {
    surface: "Dirt", distanceLabel: "4.5f",
    speedBiasPct: 85, railBias: "+",
    eIV: 1.45, epIV: 1.6, pIV: 0.65, sIV: 0.35,
    post1to3IV: 1.55, post4to7IV: 1.0, post8plusIV: 0.62,
  },
  horses: [
    h("1", "Barometric", 15.0, "P", [0, 0, 0], 0, 120, { /* jockey: Luis Saez, trainer: Timothy E. Hamm, post: 1 */ }),
    h("2", "Bit Tipsy", 20.0, "P", [0, 0, 0], 0, 120, { /* jockey: Jaime A. Torres, trainer: Eduardo Caramori, post: 2 */ }),
    h("3", "Tuxca", 30.0, "P", [0, 0, 0], 0, 120, { /* jockey: Agustin Gomez, trainer: Erick Alexander Torres, post: 3 */ }),
    h("4", "Bayou Baby", 30.0, "P", [0, 0, 0], 0, 120, { /* jockey: Adam Beschizza, trainer: Chasey Deville Pomier, post: 4 */ }),
    h("5", "Summer Dream", 20.0, "P", [0, 0, 0], 0, 120, { /* jockey: Danny Sheehy, trainer: John Ennis, post: 5 */ }),
    h("6", "By Grace", 8.0, "P", [0, 0, 0], 0, 120, { /* jockey: Jose L. Ortiz, trainer: Joe Sharp, post: 6 */ }),
    h("7", "Ruiva", 4.0, "P", [0, 0, 0], 0, 120, { /* jockey: Juan J. Hernandez, trainer: Wesley A. Ward, post: 7 */ }),
    h("8", "Just Epic", 4.5, "P", [0, 0, 0], 0, 120, { /* jockey: Brian Joseph Hernandez, Jr., trainer: Steven M. Asmussen, post: 8 */ }),
    h("9", "Epicure", 12.0, "P", [0, 0, 0], 0, 120, { /* jockey: Florent Geroux, trainer: Steven M. Asmussen, post: 9 */ }),
    h("10", "Champagne Dream", 6.0, "P", [0, 0, 0], 0, 120, { /* jockey: Irad Ortiz, Jr., trainer: Todd A. Pletcher, post: 10 */ }),
    h("11", "Traction Park", 8.0, "P", [0, 0, 0], 0, 120, { /* jockey: Tyler Gaffalione, trainer: Mark E. Casse, post: 11 */ }),
    h("12", "Bush", 3.5, "P", [0, 0, 0], 0, 120, { /* jockey: John R. Velazquez, trainer: Brian A. Lynch, post: 12 */ }),
  ],
};

// ── R4 — MCL 50000 1 1/16m Turf $67,000 ──
const race4: StaticRace = {
  raceNumber: 4, postTime: "2:16 PM",
  raceType: "MCL 50000", distance: "1 1/16m", surface: "Turf", purse: 67000, condition: "Fast",
  trackBias: {
    surface: "Turf", distanceLabel: "8.5f",
    speedBiasPct: 45, railBias: "+",
    eIV: 0.55, epIV: 1.35, pIV: 1.25, sIV: 0.85,
    post1to3IV: 1.4, post4to7IV: 0.95, post8plusIV: 0.42,
  },
  horses: [
    h("1", "Traverse City", 10.0, "P", [0, 0, 0], 0, 120, { /* jockey: Flavien Prat, trainer: Michael J. Maker, post: 1 */ }),
    h("2", "Power of Will", 15.0, "P", [0, 0, 0], 0, 120, { /* jockey: Declan Cannon, trainer: Nicholas Esler, post: 2 */ }),
    h("3", "Mush Carey", 30.0, "P", [0, 0, 0], 0, 120, { /* jockey: Danny Sheehy, trainer: Conor Murphy, post: 3 */ }),
    h("4", "Turbo Launch", 4.0, "P", [0, 0, 0], 0, 120, { /* jockey: Jose L. Ortiz, trainer: Joe Sharp, post: 4 */ }),
    h("5", "Underappreciated", 8.0, "P", [0, 0, 0], 0, 120, { /* jockey: Edgar Morales, trainer: John Ennis, post: 5 */ }),
    h("6", "Abbi Fede", 3.0, "P", [0, 0, 0], 0, 120, { /* jockey: Irad Ortiz, Jr., trainer: Joe Sharp, post: 6 */ }),
    h("7", "Feral", 6.0, "P", [0, 0, 0], 0, 120, { /* jockey: Christopher Elliott, trainer: Kenneth G. McPeek, post: 7 */ }),
    h("8", "Newman", 4.5, "P", [0, 0, 0], 0, 120, { /* jockey: Ben Curtis, trainer: Eddie Kenneally, post: 8 */ }),
    h("9", "Nyttime Story", 30.0, "P", [0, 0, 0], 0, 120, { /* jockey: Andres Calleja, trainer: Brian D. Michael, post: 9 */ }),
    h("10", "Fly Guy Mick", 12.0, "P", [0, 0, 0], 0, 120, { /* jockey: Tyler Gaffalione, trainer: Fergus Bogle, post: 10 */ }),
    h("11", "Holyrood", 30.0, "P", [0, 0, 0], 0, 120, { /* jockey: Brian Joseph Hernandez, Jr., trainer: Edward Vaughan, post: 11 */ }),
    h("12", "Bearister", 15.0, "P", [0, 0, 0], 0, 120, { /* jockey: James Graham, trainer: J. Keith Desormeaux, post: 12 */ }),
  ],
};

// ── R5 — MCL 50000 6f Dirt $67,000 ──
const race5: StaticRace = {
  raceNumber: 5, postTime: "2:47 PM",
  raceType: "MCL 50000", distance: "6f", surface: "Dirt", purse: 67000, condition: "Fast",
  trackBias: {
    surface: "Dirt", distanceLabel: "6.0f",
    speedBiasPct: 85, railBias: "+",
    eIV: 1.45, epIV: 1.6, pIV: 0.65, sIV: 0.35,
    post1to3IV: 1.55, post4to7IV: 1.0, post8plusIV: 0.62,
  },
  horses: [
    h("1", "Grant's Gretchen", 10.0, "P", [0, 0, 0], 0, 120, { /* jockey: Jaime A. Torres, trainer: Fergus Bogle, post: 1 */ }),
    h("2", "Luck of the Day", 20.0, "P", [0, 0, 0], 0, 120, { /* jockey: Oscar Villarreal, trainer: Yoni R. Orantes, post: 2 */ }),
    h("3", "Go Go Playmate", 5.0, "P", [0, 0, 0], 0, 120, { /* jockey: Irad Ortiz, Jr., trainer: Joe Sharp, post: 3 */ }),
    h("4", "Diagram", 4.5, "P", [0, 0, 0], 0, 120, { /* jockey: Axel Concepcion, trainer: W. Bret Calhoun, post: 4 */ }),
    h("5", "Santiana", 10.0, "P", [0, 0, 0], 0, 120, { /* jockey: Edgar Morales, trainer: Genaro Garcia, post: 5 */ }),
    h("6", "Lil Braveheart", 20.0, "P", [0, 0, 0], 0, 120, { /* jockey: Victor R. Carrasco, trainer: Roddina A. Barrett, post: 6 */ }),
    h("7", "Red Rainbow", 12.0, "P", [0, 0, 0], 0, 120, { /* jockey: William Antongeorgi III, trainer: Troy S. Wismer, post: 7 */ }),
    h("8", "Bourbon and Spice", 8.0, "P", [0, 0, 0], 0, 120, { /* jockey: Summer Pauly, trainer: Ed Moger, Jr., post: 8 */ }),
    h("9", "Scarce", 3.0, "P", [0, 0, 0], 0, 120, { /* jockey: Tyler Gaffalione, trainer: D. Whitworth Beckman, post: 9 */ }),
    h("10", "Ribadeo", 3.5, "P", [0, 0, 0], 0, 120, { /* jockey: Jose L. Ortiz, trainer: Albert M. Stall, Jr., post: 10 */ }),
  ],
};

// ── R6 — Stakes 5f Dirt $250,000 ──
const race6: StaticRace = {
  raceNumber: 6, postTime: "3:20 PM",
  raceType: "Stakes", distance: "5f", surface: "Dirt", purse: 250000, condition: "Fast",
  name: "Kentucky Juvenile S.",
  trackBias: {
    surface: "Dirt", distanceLabel: "5.0f",
    speedBiasPct: 85, railBias: "+",
    eIV: 1.45, epIV: 1.6, pIV: 0.65, sIV: 0.35,
    post1to3IV: 1.55, post4to7IV: 1.0, post8plusIV: 0.62,
  },
  horses: [
    h("1", "Glory Run", 15.0, "P", [0, 0, 0], 0, 120, { /* jockey: Danny Sheehy, trainer: John Ennis, post: 1 */ }),
    h("2", "Skara Brae", 1.4, "P", [0, 0, 0], 0, 120, { /* jockey: John R. Velazquez, trainer: Wesley A. Ward, post: 2 */ }),
    h("3", "American Pope", 30.0, "P", [0, 0, 0], 0, 120, { /* jockey: Christopher Elliott, trainer: Paul McEntee, post: 3 */ }),
    h("4", "Waggley", 2.0, "P", [0, 0, 0], 0, 120, { /* jockey: Joel Rosario, trainer: Wesley A. Ward, post: 4 */ }),
    h("5", "Super Saiyajin", 8.0, "P", [0, 0, 0], 0, 120, { /* jockey: Gerardo Corrales, trainer: Sergio Donjuan, post: 5 */ }),
    h("6", "Frontline Fury", 20.0, "P", [0, 0, 0], 0, 120, { /* jockey: Luan Machado, trainer: Ben Colebrook, post: 6 */ }),
    h("7", "Peak Perspective", 4.5, "P", [0, 0, 0], 0, 120, { /* jockey: Tyler Gaffalione, trainer: Ben Colebrook, post: 7 */ }),
    h("8", "Bourbon Town", 10.0, "P", [0, 0, 0], 0, 120, { /* jockey: Luis Saez, trainer: Rey Hernandez, post: 8 */ }),
  ],
};

// ── R7 — AOC 5f Turf $134,000 ──
const race7: StaticRace = {
  raceNumber: 7, postTime: "3:52 PM",
  raceType: "AOC", distance: "5f", surface: "Turf", purse: 134000, condition: "Fast",
  trackBias: {
    surface: "Turf", distanceLabel: "5.0f",
    speedBiasPct: 55, railBias: "+",
    eIV: 0.55, epIV: 1.6, pIV: 1.2, sIV: 0.65,
    post1to3IV: 1.55, post4to7IV: 0.9, post8plusIV: 0.4,
  },
  horses: [
    h("1", "Fancy Caber Neigh", 15.0, "P", [0, 0, 0], 0, 120, { /* jockey: Ben Curtis, trainer: William E. Morey, post: 1 */ }),
    h("2", "Shoot It True", 1.4, "P", [0, 0, 0], 0, 120, { /* jockey: Joel Rosario, trainer: Wesley A. Ward, post: 2 */ }),
    h("3", "I'm Mo Joke", 20.0, "P", [0, 0, 0], 0, 120, { /* jockey: Brian Joseph Hernandez, Jr., trainer: Joe Sharp, post: 3 */ }),
    h("4", "Cart Girl Sam", 15.0, "P", [0, 0, 0], 0, 120, { /* jockey: Tyler Gaffalione, trainer: Rohan G. Crichton, post: 4 */ }),
    h("5", "Justinqueso", 8.0, "P", [0, 0, 0], 0, 120, { /* jockey: Julien R. Leparoux, trainer: Ian R. Wilkes, post: 5 */ }),
    h("6", "High Fashion Kate", 10.0, "P", [0, 0, 0], 0, 120, { /* jockey: Edgar Morales, trainer: Jordan Blair, post: 6 */ }),
    h("7", "Satin Blue", 8.0, "P", [0, 0, 0], 0, 120, { /* jockey: Jose L. Ortiz, trainer: Joe Sharp, post: 7 */ }),
    h("8", "Caberneigh", 50.0, "P", [0, 0, 0], 0, 120, { /* jockey: John McKee, trainer: Scott W. Barker, post: 8 */ }),
    h("9", "Roja", 4.0, "P", [0, 0, 0], 0, 120, { /* jockey: Irad Ortiz, Jr., trainer: H. Graham Motion, post: 9 */ }),
    h("10", "Rosato", 6.0, "P", [0, 0, 0], 0, 120, { /* jockey: Luis Saez, trainer: Ian R. Wilkes, post: 10 */ }),
    h("11", "Tempting Eve", 12.0, "P", [0, 0, 0], 0, 120, { /* jockey: John R. Velazquez, trainer: Chris A. Hartman, post: 11 */ }),
    h("12", "Gladriel", 30.0, "P", [0, 0, 0], 0, 120, { /* jockey: Luan Machado, trainer: Cody W. Axmaker, post: 12 */ }),
  ],
};

// ── R8 — Starter Allowance 7f Dirt $83,000 ──
const race8: StaticRace = {
  raceNumber: 8, postTime: "4:25 PM",
  raceType: "Starter Allowance", distance: "7f", surface: "Dirt", purse: 83000, condition: "Fast",
  trackBias: {
    surface: "Dirt", distanceLabel: "7.0f",
    speedBiasPct: 85, railBias: "+",
    eIV: 1.45, epIV: 1.6, pIV: 0.65, sIV: 0.35,
    post1to3IV: 1.55, post4to7IV: 1.0, post8plusIV: 0.62,
  },
  horses: [
    h("1", "Norwich", 4.5, "P", [0, 0, 0], 0, 120, { /* jockey: Flavien Prat, trainer: Michael J. Maker, post: 1 */ }),
    h("2", "Free Advice", 15.0, "P", [0, 0, 0], 0, 120, { /* jockey: Brian Joseph Hernandez, Jr., trainer: Tommy Humphries, post: 2 */ }),
    h("3", "Sharons Beach", 2.5, "P", [0, 0, 0], 0, 120, { /* jockey: Irad Ortiz, Jr., trainer: Jonathan Thomas, post: 3 */ }),
    h("4", "Mo Work", 4.0, "P", [0, 0, 0], 0, 120, { /* jockey: Luis Saez, trainer: Mark Simms, Jr., post: 4 */ }),
    h("5", "Gordon's Legacy", 6.0, "P", [0, 0, 0], 0, 120, { /* jockey: Edgar Morales, trainer: Chris A. Hartman, post: 5 */ }),
    h("6", "Good Mojo", 12.0, "P", [0, 0, 0], 0, 120, { /* jockey: Jose L. Ortiz, trainer: Grant T. Forster, post: 6 */ }),
    h("7", "South Bend Tom", 6.0, "P", [0, 0, 0], 0, 120, { /* jockey: Tyler Gaffalione, trainer: Albert M. Stall, Jr., post: 7 */ }),
    h("8", "Speedstorm", 12.0, "P", [0, 0, 0], 0, 120, { /* jockey: Joel Rosario, trainer: Ron Moquett, post: 8 */ }),
    h("9", "Sweet Freedom", 8.0, "P", [0, 0, 0], 0, 120, { /* jockey: Alex Achard, trainer: Robert Medina, post: 9 */ }),
    h("10", "Just Like Max", 30.0, "P", [0, 0, 0], 0, 120, { /* jockey: Christopher Elliott, trainer: Genaro Garcia, post: 10 */ }),
  ],
};

// ── R9 — Stakes 1 1/2m Dirt $200,000 ──
const race9: StaticRace = {
  raceNumber: 9, postTime: "4:56 PM",
  raceType: "Stakes", distance: "1 1/2m", surface: "Dirt", purse: 200000, condition: "Fast",
  name: "Isaac Murphy Marathon S.",
  trackBias: {
    surface: "Dirt", distanceLabel: "12.0f",
    speedBiasPct: 62, railBias: "+",
    eIV: 1.1, epIV: 1.2, pIV: 0.9, sIV: 0.8,
    post1to3IV: 1.25, post4to7IV: 1.0, post8plusIV: 0.78,
  },
  horses: [
    h("1", "No Bien Ni Mal (BRZ)", 3.0, "P", [0, 0, 0], 0, 120, { /* jockey: Joel Rosario, trainer: Paulo H. Lobo, post: 1 */ }),
    h("2", "Parchment Party", 2.0, "P", [0, 0, 0], 0, 120, { /* jockey: John R. Velazquez, trainer: William I. Mott, post: 2 */ }),
    h("3", "Timeout", 12.0, "P", [0, 0, 0], 0, 120, { /* jockey: Junior Alvarado, trainer: William I. Mott, post: 3 */ }),
    h("4", "Digital Ops", 8.0, "P", [0, 0, 0], 0, 120, { /* jockey: Tyler Gaffalione, trainer: Saffie A. Joseph, Jr., post: 4 */ }),
    h("5", "Interceptor", 6.0, "P", [0, 0, 0], 0, 120, { /* jockey: Flavien Prat, trainer: Michael J. Maker, post: 5 */ }),
    h("6", "Makes Sense", 15.0, "P", [0, 0, 0], 0, 120, { /* jockey: Luis Saez, trainer: Chad Summers, post: 6 */ }),
    h("7", "Johny's Rendezvous", 20.0, "P", [0, 0, 0], 0, 120, { /* jockey: Jaime A. Torres, trainer: Philip A. Bauer, post: 7 */ }),
    h("8", "Wynstock", 4.5, "P", [0, 0, 0], 0, 120, { /* jockey: Irad Ortiz, Jr., trainer: Brad H. Cox, post: 8 */ }),
    h("9", "Stowaway", 12.0, "P", [0, 0, 0], 0, 120, { /* jockey: Jose L. Ortiz, trainer: D. Whitworth Beckman, post: 9 */ }),
  ],
};

// ── R10 — CLM 30000 1 1/16m Turf $62,000 ──
const race10: StaticRace = {
  raceNumber: 10, postTime: "5:27 PM",
  raceType: "CLM 30000", distance: "1 1/16m", surface: "Turf", purse: 62000, condition: "Fast",
  trackBias: {
    surface: "Turf", distanceLabel: "8.5f",
    speedBiasPct: 45, railBias: "+",
    eIV: 0.55, epIV: 1.35, pIV: 1.25, sIV: 0.85,
    post1to3IV: 1.4, post4to7IV: 0.95, post8plusIV: 0.42,
  },
  horses: [
    h("1", "Sussudio", 30.0, "P", [0, 0, 0], 0, 120, { /* jockey: Adam Beschizza, trainer: Jeff A. Hiles, post: 1 */ }),
    h("2", "Austin High", 6.0, "P", [0, 0, 0], 0, 120, { /* jockey: Brian Joseph Hernandez, Jr., trainer: Thomas Drury, Jr., post: 2 */ }),
    h("3", "Mustang Lady", 20.0, "P", [0, 0, 0], 0, 120, { /* jockey: Danny Sheehy, trainer: J. Kent Sweezey, post: 3 */ }),
    h("4", "Oak Alley", 8.0, "P", [0, 0, 0], 0, 120, { /* jockey: Summer Pauly, trainer: Ed Moger, Jr., post: 4 */ }),
    h("5", "Got Gone", 30.0, "P", [0, 0, 0], 0, 120, { /* jockey: Alex Achard, trainer: John Ennis, post: 5 */ }),
    h("6", "Never Really Know (IRE)", 3.5, "P", [0, 0, 0], 0, 120, { /* jockey: Luis Saez, trainer: Norm W. Casse, post: 6 */ }),
    h("7", "Fashion Affirmed", 30.0, "P", [0, 0, 0], 0, 120, { /* jockey: Jann N. Hernandez, trainer: Guber Gorostieta, post: 7 */ }),
    h("8", "Egyptian Candy", 20.0, "P", [0, 0, 0], 0, 120, { /* jockey: Gabriel Saez, trainer: Daniel Leitch, post: 8 */ }),
    h("9", "Twolatebabydoll (FR)", 2.5, "P", [0, 0, 0], 0, 120, { /* jockey: Jose L. Ortiz, trainer: Albert M. Stall, Jr., post: 9 */ }),
    h("10", "Kittens Stormy Gal", 15.0, "P", [0, 0, 0], 0, 120, { /* jockey: James Graham, trainer: Walter M. Bindner, Jr., post: 10 */ }),
    h("11", "Honor Azteca", 12.0, "P", [0, 0, 0], 0, 120, { /* jockey: Junior Alvarado, trainer: J. Keith Desormeaux, post: 11 */ }),
    h("12", "Heart Spin", 4.5, "P", [0, 0, 0], 0, 120, { /* jockey: Edgar Morales, trainer: Anna Navarrete, post: 12 */ }),
  ],
};

export const cd20260429Card: StaticRace[] = [race1, race2, race3, race4, race5, race6, race7, race8, race9, race10];
