// Churchill Downs — 2026-04-29
// Generated by scripts/gen_cd_ts.py from data/cd-2026-04-29/raw-entries.json
// Data source: BRIS Ultimate PPs PDF (parsed via scripts/parse_bris_pdf.py).
// Track bias uses CD spring-meet defaults (cd-context.ts CD_DEFAULT_BIASES).

import type { StaticRace, StaticHorse } from "./keeneland-apr18";

const h = (
  program: string, name: string, ml: number, style: string,
  beyers: number[], days: number, weight: number,
  extras: Partial<StaticHorse> = {}
): StaticHorse => ({
  program, name, mlOdds: ml, style,
  last3Beyer: beyers, daysSinceLast: days, weight,
  ...extras,
});

// ── R1 — Clm  16000 1m Dirt $55,000 ──
const race1: StaticRace = {
  raceNumber: 1, postTime: "12:45 PM",
  raceType: "Clm  16000", distance: "1m", surface: "Dirt", purse: 55000, condition: "Fast",
  trackBias: {
    surface: "Dirt", distanceLabel: "8.5f",
    speedBiasPct: 62, railBias: "+",
    eIV: 1.1, epIV: 1.2, pIV: 0.9, sIV: 0.8,
    post1to3IV: 1.25, post4to7IV: 1.0, post8plusIV: 0.78,
  },
  horses: [
    h("1", "Empire Builder", 2.5, "E", [78, 81, 85], 45, 118, { primePower: 129.9, currentClass: 114.5, earlyPaceLast: 95, latePaceLast: 69, mudPct: 18 }), // jockey: Tyler Gaffalione, trainer: Armando Hernandez, post: 1
    h("2", "Nip N Tuck", 15.0, "EP", [76, 84, 77], 32, 118, { primePower: 119.0, earlyPaceLast: 82, latePaceLast: 70, mudPct: 15 }), // jockey: Luan Machado, trainer: Barry L. King, post: 2
    h("3", "Charbon", 10.0, "EP", [81, 46, 81], 41, 118, { primePower: 112.8, earlyPaceLast: 80, latePaceLast: 82, mudPct: 16 }), // jockey: Edgar Morales, trainer: Chasey D. Pomier, post: 3
    h("4", "My Noble Knight", 3.0, "P", [83, 85, 93], 27, 118, { primePower: 125.8, currentClass: 113.9, earlyPaceLast: 76, latePaceLast: 80, mudPct: 11 }), // jockey: Jose L. Ortiz, trainer: Kinnon Larose, post: 4
    h("5", "Tres Soles", 8.0, "S", [72, 77, 85], 18, 118, { primePower: 118.3, earlyPaceLast: 83, latePaceLast: 54, mudPct: 18 }), // jockey: Gabriel Saez, trainer: William Stinson Jr., post: 5
    h("6", "Raising Kane", 15.0, "EP", [76, 77, 64], 53, 118, { primePower: 112.8, earlyPaceLast: 89, latePaceLast: 86, mudPct: 20 }), // jockey: Corey J. Lanerie, trainer: J. Keith Desormeaux, post: 6
    h("7", "Quokka", 6.0, "S", [83, 86, 76], 35, 118, { primePower: 123.8, currentClass: 113.5, earlyPaceLast: 89, latePaceLast: 83, mudPct: 8 }), // jockey: Agustin Gomez, trainer: Cirilo Gorostieta, post: 7
    h("8", "National Eclipse", 3.5, "EP", [87, 83, 75], 52, 118, { primePower: 121.2, earlyPaceLast: 81, latePaceLast: 91, mudPct: 16 }), // jockey: Irad Ortiz Jr., trainer: Robertino Diodoro, post: 8
  ],
};

// ── R2 — Clm  25000 6 1/2f Dirt $64,000 ──
const race2: StaticRace = {
  raceNumber: 2, postTime: "1:15 PM",
  raceType: "Clm  25000", distance: "6 1/2f", surface: "Dirt", purse: 64000, condition: "Fast",
  trackBias: {
    surface: "Dirt", distanceLabel: "6.0f",
    speedBiasPct: 85, railBias: "+",
    eIV: 1.45, epIV: 1.6, pIV: 0.65, sIV: 0.35,
    post1to3IV: 1.55, post4to7IV: 1.0, post8plusIV: 0.62,
  },
  horses: [
    h("1", "Barksdale", 3.0, "E", [71, 92, 84], 59, 118, { primePower: 126.4, currentClass: 113.7, earlyPaceLast: 90, latePaceLast: 66, mudPct: 17 }), // jockey: Tyler Gaffalione, trainer: David Jacobson, post: 1
    h("2", "Chiringo", 10.0, "P", [59, 82, 73], 33, 118, { primePower: 116.3, earlyPaceLast: 83, latePaceLast: 62, mudPct: 15 }), // jockey: Edgar Morales, trainer: Genaro Garcia, post: 2
    h("3", "Altobelli", 20.0, "E", [50, 83, 67], 15, 108, { primePower: 112.6, earlyPaceLast: 95, latePaceLast: 38, mudPct: 15 }), // jockey: Cesar Diaz, trainer: Nery Alvarez, post: 3
    h("4", "Real Macho", 3.5, "EP", [85, 86, 79], 47, 120, { primePower: 121.8, currentClass: 113.9, earlyPaceLast: 72, latePaceLast: 96, mudPct: 16 }), // jockey: Micah J. Husbands, trainer: Rohan G. Crichton, post: 4
    h("5", "Highly Flammable", 1.8, "P", [89, 87, 82], 41, 118, { primePower: 126.8, currentClass: 114.6, earlyPaceLast: 89, latePaceLast: 94, mudPct: 17 }), // jockey: Irad Ortiz Jr., trainer: Joe Sharp, post: 5
    h("6", "Mister Mmmmm", 3.0, "E", [52, 86, 81], 44, 118, { primePower: 117.0, earlyPaceLast: 101, latePaceLast: 44, mudPct: 15 }), // jockey: Jose L. Ortiz, trainer: Joe Sharp, post: 6
    h("7", "Charbonnay", 20.0, "P", [72, 77, 82], 118, 108, { primePower: 115.8, earlyPaceLast: 93, latePaceLast: 67, mudPct: 16 }), // jockey: Cesar Orantes, trainer: Nery Alvarez, post: 7
  ],
};

// ── R3 — Mdn 120k 4 1/2f Dirt $120,000 ──
const race3: StaticRace = {
  raceNumber: 3, postTime: "1:45 PM",
  raceType: "Mdn 120k", distance: "4 1/2f", surface: "Dirt", purse: 120000, condition: "Fast",
  trackBias: {
    surface: "Dirt", distanceLabel: "6.0f",
    speedBiasPct: 85, railBias: "+",
    eIV: 1.45, epIV: 1.6, pIV: 0.65, sIV: 0.35,
    post1to3IV: 1.55, post4to7IV: 1.0, post8plusIV: 0.62,
  },
  horses: [
    h("1", "Barometric", 15.0, "NA", [0, 0, 0], 0, 119, { mudPct: 16 }), // jockey: Luis Saez, trainer: Timothy E. Hamm, post: 1
    h("2", "Bit Tipsy", 20.0, "NA", [0, 0, 0], 0, 119, { mudPct: 19 }), // jockey: Jaime A. Torres, trainer: Eduardo Caramori, post: 2
    h("3", "Tuxca", 30.0, "NA", [0, 0, 0], 0, 119, { mudPct: 13 }), // jockey: Agustin Gomez, trainer: Erick A. Torres, post: 3
    h("4", "Bayou Baby", 30.0, "NA", [0, 0, 0], 0, 119, { mudPct: 13 }), // jockey: Adam Beschizza, trainer: Chasey D. Pomier, post: 4
    h("5", "Summer Dream", 20.0, "NA", [0, 0, 0], 0, 119, { mudPct: 18 }), // jockey: Danny Sheehy, trainer: John Ennis, post: 5
    h("6", "By Grace", 8.0, "NA", [0, 0, 0], 0, 119, { mudPct: 17 }), // jockey: Jose L. Ortiz, trainer: Joe Sharp, post: 6
    h("7", "Ruiva", 4.0, "NA", [0, 0, 0], 0, 119, { mudPct: 17 }), // jockey: Juan J. Hernandez, trainer: Wesley A. Ward, post: 7
    h("8", "Just Epic", 4.5, "NA", [0, 0, 0], 0, 119, {}), // jockey: Brian J. Hernandez Jr., trainer: Steven M. Asmussen, post: 8
    h("9", "Epicure", 12.0, "NA", [0, 0, 0], 0, 119, {}), // jockey: Florent Geroux, trainer: Steven M. Asmussen, post: 9
    h("10", "Champagne Dream", 6.0, "NA", [0, 0, 0], 0, 119, {}), // jockey: Irad Ortiz Jr., trainer: Todd A. Pletcher, post: 10
    h("11", "Traction Park", 8.0, "NA", [0, 0, 0], 0, 119, { mudPct: 22 }), // jockey: Tyler Gaffalione, trainer: Mark E. Casse, post: 11
    h("12", "Bush", 3.5, "NA", [0, 0, 0], 0, 119, { mudPct: 17 }), // jockey: John R. Velazquez, trainer: Brian A. Lynch, post: 12
  ],
};

// ── R4 — MC 50000 1 1/16m Turf $67,000 ──
const race4: StaticRace = {
  raceNumber: 4, postTime: "2:16 PM",
  raceType: "MC 50000", distance: "1 1/16m", surface: "Turf", purse: 67000, condition: "Fast",
  trackBias: {
    surface: "Turf", distanceLabel: "routes",
    speedBiasPct: 45, railBias: "+",
    eIV: 0.55, epIV: 1.35, pIV: 1.25, sIV: 0.85,
    post1to3IV: 1.4, post4to7IV: 0.95, post8plusIV: 0.42,
  },
  horses: [
    h("1", "Traverse City", 10.0, "NA", [60, 0, 0], 47, 118, { primePower: 112.1, earlyPaceLast: 83, latePaceLast: 66, mudPct: 16 }), // jockey: Flavien Prat, trainer: Michael J. Maker, post: 1
    h("2", "Power of Will", 15.0, "E", [71, 74, 70], 54, 126, { primePower: 103.3, earlyPaceLast: 89, latePaceLast: 71, mudPct: 12 }), // jockey: Declan Cannon, trainer: Nicholas Esler, post: 2
    h("3", "Mush Carey", 30.0, "NA", [75, 0, 0], 39, 118, { primePower: 115.1, earlyPaceLast: 85, latePaceLast: 81, mudPct: 15 }), // jockey: Danny Sheehy, trainer: Conor Murphy, post: 3
    h("4", "Turbo Launch", 4.0, "EP", [70, 75, 75], 38, 118, { primePower: 116.8, earlyPaceLast: 86, latePaceLast: 82, mudPct: 15 }), // jockey: Jose L. Ortiz, trainer: Joe Sharp, post: 4
    h("5", "Underappreciated", 8.0, "EP", [70, 76, 68], 18, 118, { primePower: 109.4, currentClass: 110.5, earlyPaceLast: 88, latePaceLast: 50, mudPct: 16 }), // jockey: Edgar Morales, trainer: John Ennis, post: 5
    h("6", "Abbi Fede", 3.0, "E", [83, 83, 0], 32, 126, { primePower: 129.2, currentClass: 111.1, mudPct: 16 }), // jockey: Irad Ortiz Jr., trainer: Joe Sharp, post: 6
    h("7", "Feral", 6.0, "EP", [70, 74, 62], 19, 118, { primePower: 117.4, currentClass: 110.5, earlyPaceLast: 90, latePaceLast: 64, mudPct: 15 }), // jockey: Christopher Elliott, trainer: Kenneth G. Mcpeek, post: 7
    h("8", "Newman", 4.5, "P", [67, 78, 69], 18, 118, { primePower: 112.4, earlyPaceLast: 87, latePaceLast: 46, mudPct: 17 }), // jockey: Ben Curtis, trainer: Eddie Kenneally, post: 8
    h("9", "Nyttime Story", 30.0, "NA", [77, 65, 63], 35, 126, { primePower: 112.0, earlyPaceLast: 82, latePaceLast: 83, mudPct: 19 }), // jockey: Andres Calleja, trainer: Brian D. Michael, post: 9
    h("10", "Fly Guy Mick", 12.0, "P", [75, 75, 87], 56, 126, { primePower: 117.3, earlyPaceLast: 68, latePaceLast: 68, mudPct: 11 }), // jockey: Tyler Gaffalione, trainer: Fergus Bogle, post: 10
    h("11", "Holyrood", 30.0, "S", [75, 75, 64], 49, 118, { primePower: 114.7, earlyPaceLast: 79, latePaceLast: 81, mudPct: 11 }), // jockey: Brian J. Hernandez Jr., trainer: Edward Vaughan, post: 11
    h("12", "Bearister", 15.0, "P", [61, 77, 80], 20, 118, { primePower: 111.7, earlyPaceLast: 90, latePaceLast: 44, mudPct: 22 }), // jockey: James Graham, trainer: J. Keith Desormeaux, post: 12
    h("13", "Ur Benja", 15.0, "NA", [70, 67, 0], 18, 118, { primePower: 106.1, earlyPaceLast: 72, latePaceLast: 64, mudPct: 14 }), // jockey: Gabriel Saez, trainer: Jose L. Aranha, post: 13
    h("14", "Amberssohn", 30.0, "S", [65, 0, 0], 48, 118, { primePower: 101.8, earlyPaceLast: 74, latePaceLast: 66, mudPct: 18 }), // jockey: Adam Beschizza, trainer: Thomas Molloy, post: 14
    h("15", "The Fed's Plot", 12.0, "EP", [74, 69, 73], 48, 126, { primePower: 109.3, earlyPaceLast: 81, latePaceLast: 71, mudPct: 19 }), // jockey: Adam Beschizza, trainer: Kelsey Danner, post: 15
  ],
};

// ── R5 — MC 50000 6f Dirt $67,000 ──
const race5: StaticRace = {
  raceNumber: 5, postTime: "2:47 PM",
  raceType: "MC 50000", distance: "6f", surface: "Dirt", purse: 67000, condition: "Fast",
  trackBias: {
    surface: "Dirt", distanceLabel: "6.0f",
    speedBiasPct: 85, railBias: "+",
    eIV: 1.45, epIV: 1.6, pIV: 0.65, sIV: 0.35,
    post1to3IV: 1.55, post4to7IV: 1.0, post8plusIV: 0.62,
  },
  horses: [
    h("1", "Grant's Gretchen", 10.0, "NA", [70, 71, 0], 26, 118, { primePower: 111.3, earlyPaceLast: 85, latePaceLast: 79, mudPct: 17 }), // jockey: Jaime A. Torres, trainer: Fergus Bogle, post: 1
    h("2", "Luck of the Day", 20.0, "NA", [68, 0, 0], 21, 118, { primePower: 108.1, currentClass: 110.0, earlyPaceLast: 69, latePaceLast: 81, mudPct: 18 }), // jockey: Oscar Villarreal, trainer: Yoni R. Orantes, post: 2
    h("3", "Go Go Playmate", 5.0, "E", [71, 62, 0], 46, 118, { primePower: 113.7, earlyPaceLast: 99, latePaceLast: 71, mudPct: 17 }), // jockey: Irad Ortiz Jr., trainer: Joe Sharp, post: 3
    h("4", "Diagram", 4.5, "E", [77, 74, 77], 299, 125, { primePower: 116.1, currentClass: 109.9, earlyPaceLast: 94, latePaceLast: 68, mudPct: 19 }), // jockey: Axel Concepcion, trainer: W. Bret Calhoun, post: 4
    h("5", "Santiana", 10.0, "E", [72, 71, 69], 22, 118, { primePower: 113.9, currentClass: 109.5, earlyPaceLast: 94, latePaceLast: 70, mudPct: 19 }), // jockey: Edgar Morales, trainer: Genaro Garcia, post: 5
    h("6", "Lil Braveheart", 20.0, "NA", [64, 0, 0], 26, 118, { primePower: 105.1, earlyPaceLast: 74, latePaceLast: 82, mudPct: 16 }), // jockey: Victor R. Carrasco, trainer: Roddina A. Barrett, post: 6
    h("7", "Red Rainbow", 12.0, "E", [72, 61, 67], 21, 118, { primePower: 113.6, earlyPaceLast: 88, latePaceLast: 70, mudPct: 16 }), // jockey: William Antongeorgi III, trainer: Troy S. Wismer, post: 7
    h("8", "Bourbon and Spice", 8.0, "E", [76, 74, 0], 22, 113, { primePower: 115.6, earlyPaceLast: 96, latePaceLast: 77, mudPct: 17 }), // jockey: Summer Pauly, trainer: Ed Moger Jr., post: 8
    h("9", "Scarce", 3.0, "NA", [71, 70, 71], 226, 125, { primePower: 111.8, earlyPaceLast: 76, latePaceLast: 70, mudPct: 17 }), // jockey: Tyler Gaffalione, trainer: D. Whitworth Beckman, post: 9
    h("10", "Ribadeo", 3.5, "EP", [67, 76, 0], 48, 118, { primePower: 108.2, earlyPaceLast: 73, latePaceLast: 64, mudPct: 16 }), // jockey: Jose L. Ortiz, trainer: Albert M. Stall Jr., post: 10
  ],
};

// ── R6 — KyJuvnileB250K 5f Dirt $250,000 ──
const race6: StaticRace = {
  raceNumber: 6, postTime: "3:20 PM",
  raceType: "KyJuvnileB250K", distance: "5f", surface: "Dirt", purse: 250000, condition: "Fast",
  trackBias: {
    surface: "Dirt", distanceLabel: "6.0f",
    speedBiasPct: 85, railBias: "+",
    eIV: 1.45, epIV: 1.6, pIV: 0.65, sIV: 0.35,
    post1to3IV: 1.55, post4to7IV: 1.0, post8plusIV: 0.62,
  },
  horses: [
    h("1", "Glory Run", 15.0, "NA", [0, 0, 0], 0, 115, { mudPct: 20 }), // jockey: Danny Sheehy, trainer: John Ennis, post: 1
    h("2", "Skara Brae", 1.4, "E", [0, 0, 0], 20, 117, { primePower: 132.8, currentClass: 116.0 }), // jockey: John R. Velazquez, trainer: Wesley A. Ward, post: 2
    h("3", "American Pope", 30.0, "NA", [0, 0, 0], 13, 118, { primePower: 109.6, mudPct: 17 }), // jockey: Christopher Elliott, trainer: Paul Mcentee, post: 3
    h("4", "Waggley", 2.0, "E", [0, 0, 0], 21, 117, { primePower: 132.1, currentClass: 115.9 }), // jockey: Joel Rosario, trainer: Wesley A. Ward, post: 4
    h("5", "Super Saiyajin", 8.0, "E", [0, 0, 0], 13, 118, { primePower: 119.2, currentClass: 113.2, mudPct: 15 }), // jockey: Gerardo Corrales, trainer: Sergio Donjuan, post: 5
    h("6", "Frontline Fury", 20.0, "P", [0, 0, 0], 21, 115, { primePower: 117.8, mudPct: 14 }), // jockey: Luan Machado, trainer: Ben Colebrook, post: 6
    h("7", "Peak Perspective", 4.5, "S", [0, 0, 0], 14, 115, { primePower: 116.9, mudPct: 16 }), // jockey: Tyler Gaffalione, trainer: Ben Colebrook, post: 7
    h("8", "Bourbon Town", 10.0, "P", [0, 0, 0], 26, 118, { primePower: 120.7, mudPct: 16 }), // jockey: Luis Saez, trainer: Rey Hernandez, post: 8
  ],
};

// ── R7 — OC  80000n2x 5f Turf $134,000 ──
const race7: StaticRace = {
  raceNumber: 7, postTime: "3:52 PM",
  raceType: "OC  80000n2x", distance: "5f", surface: "Turf", purse: 134000, condition: "Fast",
  trackBias: {
    surface: "Turf", distanceLabel: "5.5f",
    speedBiasPct: 55, railBias: "+",
    eIV: 0.55, epIV: 1.6, pIV: 1.2, sIV: 0.65,
    post1to3IV: 1.55, post4to7IV: 0.9, post8plusIV: 0.4,
  },
  horses: [
    h("1", "Fancy Caber Neigh", 15.0, "E", [44, 88, 85], 82, 122, { primePower: 120.5, earlyPaceLast: 95, latePaceLast: 29, mudPct: 18 }), // jockey: Ben Curtis, trainer: William E. Morey, post: 1
    h("2", "Shoot It True", 1.4, "P", [87, 90, 0], 25, 122, { primePower: 149.9, currentClass: 116.4, earlyPaceLast: 83, latePaceLast: 88, mudPct: 17 }), // jockey: Joel Rosario, trainer: Wesley A. Ward, post: 2
    h("3", "I'm Mo Joke", 20.0, "P", [85, 84, 78], 53, 122, { primePower: 134.7, earlyPaceLast: 93, latePaceLast: 82, mudPct: 17 }), // jockey: Brian J. Hernandez Jr., trainer: Joe Sharp, post: 3
    h("4", "Cart Girl Sam", 15.0, "EP", [0, 0, 0], 18, 122, { primePower: 134.8, mudPct: 16 }), // jockey: Tyler Gaffalione, trainer: Rohan G. Crichton, post: 4
    h("5", "Justinqueso", 8.0, "P", [91, 88, 0], 46, 122, { primePower: 137.6, mudPct: 20 }), // jockey: Julien R. Leparoux, trainer: Ian R. Wilkes, post: 5
    h("6", "High Fashion Kate", 10.0, "EP", [87, 84, 0], 328, 122, { primePower: 124.5, currentClass: 115.4, earlyPaceLast: 96, latePaceLast: 79, mudPct: 14 }), // jockey: Edgar Morales, trainer: Jordan Blair, post: 6
    h("7", "Satin Blue", 8.0, "S", [89, 77, 0], 304, 122, { primePower: 135.1, mudPct: 13 }), // jockey: Jose L. Ortiz, trainer: Joe Sharp, post: 7
    h("8", "Caberneigh", 50.0, "E", [69, 58, 0], 25, 122, { primePower: 108.5, earlyPaceLast: 92, latePaceLast: 66, mudPct: 17 }), // jockey: John Mckee, trainer: Scott W. Barker, post: 8
    h("9", "Roja", 4.0, "EP", [91, 91, 87], 291, 122, { primePower: 148.9, currentClass: 116.0, earlyPaceLast: 100, latePaceLast: 86, mudPct: 15 }), // jockey: Irad Ortiz Jr., trainer: H. Graham Motion, post: 9
    h("10", "Rosato", 6.0, "EP", [85, 81, 52], 25, 122, { primePower: 133.1, earlyPaceLast: 89, latePaceLast: 84, mudPct: 17 }), // jockey: Luis Saez, trainer: Ian R. Wilkes, post: 10
    h("11", "Tempting Eve", 12.0, "EP", [87, 73, 75], 54, 124, { primePower: 124.5, earlyPaceLast: 103, latePaceLast: 76, mudPct: 16 }), // jockey: John R. Velazquez, trainer: Chris A. Hartman, post: 11
    h("12", "Gladriel", 30.0, "E", [82, 85, 0], 34, 122, { primePower: 127.5, earlyPaceLast: 94, latePaceLast: 80, mudPct: 16 }), // jockey: Luan Machado, trainer: Cody W. Axmaker, post: 12
    h("13", "J Z's Last Schance", 30.0, "S", [79, 75, 79], 49, 122, { primePower: 119.3, earlyPaceLast: 82, latePaceLast: 89, mudPct: 28 }), // jockey: Axel Concepcion, trainer: Joel Zawitz, post: 13
  ],
};

// ── R8 — Alw  50000s 7f Dirt $83,000 ──
const race8: StaticRace = {
  raceNumber: 8, postTime: "4:25 PM",
  raceType: "Alw  50000s", distance: "7f", surface: "Dirt", purse: 83000, condition: "Fast",
  trackBias: {
    surface: "Dirt", distanceLabel: "6.0f",
    speedBiasPct: 85, railBias: "+",
    eIV: 1.45, epIV: 1.6, pIV: 0.65, sIV: 0.35,
    post1to3IV: 1.55, post4to7IV: 1.0, post8plusIV: 0.62,
  },
  horses: [
    h("1", "Norwich", 4.5, "EP", [88, 88, 87], 41, 124, { primePower: 125.8, currentClass: 114.5, earlyPaceLast: 90, latePaceLast: 85, mudPct: 17 }), // jockey: Flavien Prat, trainer: Michael J. Maker, post: 1
    h("2", "Free Advice", 15.0, "EP", [81, 82, 69], 19, 126, { primePower: 118.0, earlyPaceLast: 79, latePaceLast: 88, mudPct: 16 }), // jockey: Brian J. Hernandez Jr., trainer: Tommy Humphries, post: 2
    h("3", "Sharons Beach", 2.5, "E", [88, 91, 94], 21, 118, { primePower: 133.1, currentClass: 115.3, earlyPaceLast: 90, latePaceLast: 82, mudPct: 20 }), // jockey: Irad Ortiz Jr., trainer: Jonathan Thomas, post: 3
    h("4", "Mo Work", 4.0, "EP", [97, 73, 80], 13, 124, { primePower: 129.1, earlyPaceLast: 85, latePaceLast: 101, mudPct: 14 }), // jockey: Luis Saez, trainer: Mark Simms Jr., post: 4
    h("5", "Gordon's Legacy", 6.0, "P", [86, 82, 0], 33, 124, { primePower: 124.2, currentClass: 113.8, earlyPaceLast: 99, latePaceLast: 84, mudPct: 18 }), // jockey: Edgar Morales, trainer: Chris A. Hartman, post: 5
    h("6", "Good Mojo", 12.0, "EP", [79, 80, 86], 100, 124, { primePower: 118.8, earlyPaceLast: 86, latePaceLast: 75, mudPct: 15 }), // jockey: Jose L. Ortiz, trainer: Grant T. Forster, post: 6
    h("7", "South Bend Tom", 6.0, "EP", [57, 88, 60], 123, 124, { primePower: 112.8, earlyPaceLast: 86, latePaceLast: 68, mudPct: 19 }), // jockey: Tyler Gaffalione, trainer: Albert M. Stall Jr., post: 7
    h("8", "Speedstorm", 12.0, "EP", [87, 68, 0], 38, 124, { primePower: 117.2, earlyPaceLast: 96, latePaceLast: 87, mudPct: 15 }), // jockey: Joel Rosario, trainer: Ron Moquett, post: 8
    h("9", "Sweet Freedom", 8.0, "P", [82, 87, 80], 32, 124, { primePower: 125.0, earlyPaceLast: 83, latePaceLast: 88, mudPct: 20 }), // jockey: Alex Achard, trainer: Robert Medina, post: 9
    h("10", "Just Like Max", 30.0, "P", [73, 60, 78], 21, 118, { primePower: 114.1, earlyPaceLast: 82, latePaceLast: 77, mudPct: 21 }), // jockey: Christopher Elliott, trainer: Genaro Garcia, post: 10
  ],
};

// ── R9 — IMphyMthnL200K 1½ Mile Dirt $200,000 ──
const race9: StaticRace = {
  raceNumber: 9, postTime: "4:56 PM",
  raceType: "IMphyMthnL200K", distance: "1\u00bd Mile", surface: "Dirt", purse: 200000, condition: "Fast",
  trackBias: {
    surface: "Dirt", distanceLabel: "8.5f",
    speedBiasPct: 62, railBias: "+",
    eIV: 1.1, epIV: 1.2, pIV: 0.9, sIV: 0.8,
    post1to3IV: 1.25, post4to7IV: 1.0, post8plusIV: 0.78,
  },
  horses: [
    h("1", "No Bien Ni Mal", 3.0, "P", [104, 100, 0], 221, 123, { primePower: 141.6, currentClass: 120.3, earlyPaceLast: 80, latePaceLast: 113, mudPct: 29 }), // jockey: Joel Rosario, trainer: Paulo H. Lobo, post: 1
    h("2", "Parchment Party", 2.0, "P", [5, 2, 8], 32, 120, { primePower: 142.0, currentClass: 119.6, earlyPaceLast: 51, latePaceLast: 111, mudPct: 16 }), // jockey: John R. Velazquez, trainer: William I. Mott, post: 2
    h("3", "Timeout", 12.0, "P", [87, 7, 97], 32, 118, { primePower: 132.1, earlyPaceLast: 86, latePaceLast: 80, mudPct: 18 }), // jockey: Junior Alvarado, trainer: William I. Mott, post: 3
    h("4", "Digital Ops", 8.0, "E", [86, 60, 0], 48, 118, { primePower: 136.7, mudPct: 19 }), // jockey: Tyler Gaffalione, trainer: Saffie A. Joseph Jr., post: 4
    h("5", "Interceptor", 6.0, "EP", [3, 3, 96], 25, 118, { primePower: 136.6, currentClass: 118.4, earlyPaceLast: 53, latePaceLast: 98, mudPct: 15 }), // jockey: Flavien Prat, trainer: Michael J. Maker, post: 5
    h("6", "Makes Sense", 15.0, "EP", [88, 94, 91], 33, 118, { primePower: 130.9, earlyPaceLast: 76, latePaceLast: 96, mudPct: 17 }), // jockey: Luis Saez, trainer: Chad Summers, post: 6
    h("7", "Johny's Rendezvous", 20.0, "EP", [86, 92, 77], 25, 118, { primePower: 131.5, earlyPaceLast: 80, latePaceLast: 92, mudPct: 20 }), // jockey: Jaime A. Torres, trainer: Philip A. Bauer, post: 7
    h("8", "Wynstock", 4.5, "EP", [94, 80, 106], 33, 118, { primePower: 134.7, earlyPaceLast: 80, latePaceLast: 102, mudPct: 12 }), // jockey: Irad Ortiz Jr., trainer: Brad H. Cox, post: 8
    h("9", "Stowaway", 12.0, "EP", [1, 84, 0], 25, 118, { primePower: 135.0, earlyPaceLast: 44, latePaceLast: 101, mudPct: 20 }), // jockey: Jose L. Ortiz, trainer: D. Whitworth Beckman, post: 9
  ],
};

// ── R10 — Clm 30000n2L 1 1/16m Turf $62,000 ──
const race10: StaticRace = {
  raceNumber: 10, postTime: "5:27 PM",
  raceType: "Clm 30000n2L", distance: "1 1/16m", surface: "Turf", purse: 62000, condition: "Fast",
  trackBias: {
    surface: "Turf", distanceLabel: "routes",
    speedBiasPct: 45, railBias: "+",
    eIV: 0.55, epIV: 1.35, pIV: 1.25, sIV: 0.85,
    post1to3IV: 1.4, post4to7IV: 0.95, post8plusIV: 0.42,
  },
  horses: [
    h("1", "Sussudio", 30.0, "P", [68, 61, 68], 41, 118, { primePower: 102.8, earlyPaceLast: 73, latePaceLast: 73, mudPct: 17 }), // jockey: Adam Beschizza, trainer: Jeff A. Hiles, post: 1
    h("2", "Austin High", 6.0, "E", [51, 80, 63], 35, 125, { primePower: 107.3, earlyPaceLast: 83, latePaceLast: 60, mudPct: 18 }), // jockey: Brian J. Hernandez Jr., trainer: Thomas Drury Jr., post: 2
    h("3", "Mustang Lady", 20.0, "P", [72, 69, 78], 20, 125, { primePower: 108.5, earlyPaceLast: 83, latePaceLast: 79, mudPct: 19 }), // jockey: Danny Sheehy, trainer: J. Kent Sweezey, post: 3
    h("4", "Oak Alley", 8.0, "S", [77, 66, 77], 39, 120, { primePower: 120.1, earlyPaceLast: 90, latePaceLast: 73, mudPct: 12 }), // jockey: Summer Pauly, trainer: Ed Moger Jr., post: 4
    h("5", "Got Gone", 30.0, "P", [66, 72, 62], 48, 118, { primePower: 109.1, earlyPaceLast: 53, latePaceLast: 86, mudPct: 13 }), // jockey: Alex Achard, trainer: John Ennis, post: 5
    h("6", "Never Really Know", 3.5, "E", [73, 81, 77], 51, 125, { primePower: 117.6, currentClass: 111.5, earlyPaceLast: 76, latePaceLast: 76, mudPct: 11 }), // jockey: Luis Saez, trainer: Norm W. Casse, post: 6
    h("7", "Fashion Affirmed", 30.0, "P", [72, 70, 68], 41, 125, { primePower: 107.7, earlyPaceLast: 69, latePaceLast: 82, mudPct: 15 }), // jockey: Jann N. Hernandez, trainer: Guber Gorostieta, post: 7
    h("8", "Egyptian Candy", 20.0, "S", [74, 67, 70], 39, 125, { primePower: 114.8, earlyPaceLast: 81, latePaceLast: 76, mudPct: 17 }), // jockey: Gabriel Saez, trainer: Daniel Leitch, post: 8
    h("9", "Twolatebabydoll", 2.5, "P", [70, 80, 66], 54, 125, { primePower: 119.4, earlyPaceLast: 95, latePaceLast: 69 }), // jockey: Jose L. Ortiz, trainer: Albert M. Stall Jr., post: 9
    h("10", "Kittens Stormy Gal", 15.0, "E", [72, 55, 69], 34, 125, { primePower: 105.5, earlyPaceLast: 82, latePaceLast: 77, mudPct: 8 }), // jockey: James Graham, trainer: Walter M. Bindner Jr., post: 10
    h("11", "Honor Azteca", 12.0, "S", [68, 75, 72], 20, 118, { primePower: 110.8, currentClass: 111.8, earlyPaceLast: 64, latePaceLast: 77, mudPct: 14 }), // jockey: Junior Alvarado, trainer: J. Keith Desormeaux, post: 11
    h("12", "Heart Spin", 4.5, "S", [76, 83, 81], 17, 125, { primePower: 118.5, currentClass: 113.0, earlyPaceLast: 79, latePaceLast: 68, mudPct: 16 }), // jockey: Edgar Morales, trainer: Anna Navarrete, post: 12
    h("13", "Texas Holiday", 4.0, "E", [73, 74, 81], 21, 125, { primePower: 117.9, earlyPaceLast: 88, latePaceLast: 52, mudPct: 15 }), // jockey: Flavien Prat, trainer: Joe Sharp, post: 13
    h("14", "Bindi", 20.0, "E", [71, 0, 0], 34, 125, { primePower: 112.1, earlyPaceLast: 90, latePaceLast: 67, mudPct: 14 }), // jockey: Ben Curtis, trainer: William E. Morey, post: 14
    h("15", "Menkaure", 10.0, "EP", [70, 60, 74], 26, 118, { primePower: 121.6, earlyPaceLast: 89, latePaceLast: 66, mudPct: 15 }), // jockey: Flavien Prat, trainer: William Walden, post: 15
    h("16", "Queen Mercedes", 12.0, "S", [73, 81, 48], 41, 125, { primePower: 115.5, earlyPaceLast: 61, latePaceLast: 92, mudPct: 18 }), // jockey: Victor Lebron, trainer: George S. Bush, post: 16
  ],
};

export const CD_2026_04_29: StaticRace[] = [race1, race2, race3, race4, race5, race6, race7, race8, race9, race10];
export const CD_2026_04_29_DATE = "2026-04-29";

// Mark class drop using currentClass vs avgClassLast3 heuristic
for (const r of CD_2026_04_29) {
  for (const horse of r.horses) {
    if (horse.currentClass && horse.avgClassLast3 && horse.currentClass < horse.avgClassLast3) {
      horse.isClassDrop = true;
    }
  }
}
